/**
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

const moduleContext = {
  "moduleId": "sap_purchasing_documents"
};
const tableConfig = {
  "tags": [
    "sap",
    "dataproduct",
    "transactional"
  ],
  "materializationType": "incremental",
  "description": "Information about purchasing documents at the item level, at the granularity of Client(System), Purchasing document number and Item number of purchasing document.",
  "columns": {
    "client_mandt": "Client (Mandant), PK",
    "purchasing_document_number_ebeln": "Purchasing Document Number, PK",
    "item_number_of_purchasing_document_ebelp": "Item Number of Purchasing Document, PK",
    "deletion_flag_loekz": "Deletion Indicator in Purchasing Document",
    "currency_key_waers": "Currency Key",
    "rfq_status_statu": "RFQ status",
    "change_date_aedat": "Purchasing Document Item Change Date",
    "short_text_txz01": "Short Text",
    "material_number_matnr": "Material Number",
    "material_number_ematn": "Material Number",
    "company_code_bukrs": "Company Code",
    "plant_werks": "Plant",
    "storage_location_lgort": "Storage Location",
    "requirement_tracking_number_bednr": "Requirement Tracking Number",
    "material_group_matkl": "Material Group",
    "number_of_purchasing_info_record_infnr": "Number of Purchasing Info Record",
    "material_number_vendor_idnlf": "Material Number Used by Vendor",
    "target_quantity_ktmng": "Target Quantity",
    "po_quantity_menge": "Purchase Order Quantity",
    "uo_m_meins": "Purchase Order Unit of Measure",
    "order_price_unit_bprme": "Order Price Unit (Purchasing)",
    "order_unit_numerator_bpumz": "Numerator for Conversion of Order Price Unit into Order Unit",
    "order_unit_denominator_bpumn": "Denominator for Conv. of Order Price Unit into Order Unit",
    "numerator_for_conversion_of_order_unit_to_base_unit_umrez": "Numerator for Conversion of Order Unit to Base Unit",
    "denominator_for_conversion_of_order_unit_to_base_unit_umren": "Denominator for Conversion of Order Unit to Base Unit",
    "price_unit_peinh": "Price unit",
    "deadline_for_submission_of_bid_agdat": "Deadline for Submission of Bid/Quotation",
    "goods_receipt_processing_time_in_days_webaz": "Goods Receipt Processing Time in Days",
    "taxcode_mwskz": "Tax on sales/purchases code",
    "settlement_group1_bonus": "Settlement Group 1 (Purchasing)",
    "stock_type_insmk": "Stock Type",
    "update_info_record_flag_spinf": "Indicator: Update Info Record",
    "price_printout_prsdr": "Price Printout",
    "estimated_price_flag_schpr": "Indicator: Estimated Price",
    "number_of_reminders_mahnz": "Number of Reminders/Expediters",
    "number_of_days_for_first_reminder_mahn1": "Number of Days for First Reminder/Expediter",
    "number_of_days_for_second_reminder_mahn2": "Number of Days for Second Reminder/Expediter",
    "number_of_days_for_third_reminder_mahn3": "Number of Days for Third Reminder/Expediter",
    "overdelivery_tolerance_limit_uebto": "Overdelivery Tolerance Limit",
    "unlimited_overdelivery_allowed_uebtk": "Indicator: Unlimited Overdelivery Allowed",
    "underdelivery_tolerance_limit_untto": "Underdelivery Tolerance Limit",
    "valuation_type_bwtar": "Valuation Type",
    "valuation_category_bwtty": "Valuation Category",
    "rejection_flag_abskz": "Rejection Indicator",
    "internal_comment_on_quotation_agmem": "Internal Comment on Quotation",
    "delivery_completed_flag_elikz": "'Delivery Completed' Indicator",
    "final_invoice_flag_erekz": "Final Invoice Indicator",
    "item_categoryin_purchasing_document_pstyp": "Item Category in Purchasing Document",
    "account_assignment_category_knttp": "Account Assignment Category",
    "consumption_posting_kzvbr": "Consumption Posting",
    "distribution_flag_for_multiple_account_assignment_vrtkz": "Distribution indicator for multiple account assignment",
    "partial_invoice_flag_twrkz": "Partial Invoice Indicator",
    "goods_receipt_flag_wepos": "Goods Receipt Indicator",
    "goods_receipt_non_valuated_weunb": "Goods Receipt, Non-Valuated",
    "invoice_receipt_flag_repos": "Invoice Receipt Indicator",
    "flag_gr_based_invoice_verification_webre": "Indicator: GR-Based Invoice Verification",
    "order_acknowledgment_requirement_kzabs": "Acknowledgment Reqd",
    "order_acknowledgment_number_labnr": "Order Acknowledgment Requirement",
    "number_of_principal_purchase_agreement_konnr": "Number of Principal Purchase Agreement",
    "item_number_of_principal_purchase_agreement_ktpnr": "Item Number of Principal Purchase Agreement",
    "reconciliation_date_for_agreed_cumulative_quantity_abdat": "Reconciliation Date for Agreed Cumulative Quantity",
    "agreed_cumulative_quantity_abftz": "Agreed Cumulative Quantity",
    "firm_zone_etfz1": "Firm Zone (Go-Ahead for Production)",
    "trade_off_zone_etfz2": "Trade-Off Zone (Go-Ahead for Materials Procurement)",
    "firm_trade_off_zones_kzstu": "Firm/Trade-Off Zones Binding with Regard to Mat. Planning",
    "exclusion_in_outline_agreement_item_with_material_class_notkz": "Exclusion in Outline Agreement Item with Material Class",
    "base_unit_of_measure_lmein": "Base Unit of Measure",
    "shipping_instructions_evers": "Shipping Instructions",
    "non_deductible_input_tax_navnw": "Non-deductible input tax",
    "standard_release_order_quantity_abmng": "Standard release order quantity",
    "date_of_price_determination_prdat": "Date of Price Determination",
    "purchasing_document_category_bstyp": "Purchasing Document Category",
    "item_affects_commitments_xoblr": "Item affects commitments",
    "manual_address_number_in_purchasing_document_item_adrnr": "Manual address number in purchasing document item",
    "condition_group_with_vendor_ekkol": "Condition Group with Vendor",
    "item_does_not_qualify_for_cash_discount_sktof": "Item Does Not Qualify for Cash Discount",
    "update_group_for_statistics_update_stafo": "Update group for statistics update",
    "planned_delivery_time_in_days_plifz": "Planned Delivery Time in Days",
    "net_weight_ntgew": "Net Weight",
    "unit_of_weight_gewei": "Unit of Weight",
    "tax_jurisdiction_txjcd": "Tax Jurisdiction",
    "flag_print_relevant_schedule_lines_exist_etdrk": "Indicator: Print-relevant schedule lines exist",
    "special_stock_flag_sobkz": "Special Stock Indicator",
    "settlement_reservation_number_arsnr": "Settlement reservation number",
    "item_number_of_the_settlement_reservation_arsps": "Item number of the settlement reservation",
    "quality_inspection_flag_cannot_be_changed_insnc": "Quality inspection indicator cannot be changed",
    "control_key_for_quality_management_in_procurement_ssqss": "Control Key for Quality Management in Procurement",
    "certificate_type_zgtyp": "Certificate type",
    "international_article_number_ean11": "International Article Number (EAN/UPC)",
    "confirmation_control_key_bstae": "Confirmation Control Key",
    "revision_level_revlv": "Revision Level",
    "fund_geber": "Fund",
    "funds_center_fistl": "Funds Center",
    "commitment_item_fipos": "Commitment item",
    "business_area_reported_to_the_partner_ko_gsber": "Business area reported to the partner",
    "assumed_business_area_of_the_business_partner_ko_pargb": "Assumed business area of the business partner",
    "profit_center_ko_prctr": "Profit Center",
    "partner_profit_center_ko_pprctr": "Partner Profit Center",
    "pricing_date_control_meprf": "Price Determination (Pricing) Date Control",
    "gross_weight_brgew": "Gross Weight",
    "volume_volum": "Volume",
    "volume_unit_voleh": "Volume Unit",
    "incoterms1_inco1": "Incoterms (Part 1)",
    "incoterms2_inco2": "Incoterms (Part 2)",
    "advance_procurement_vorab": "Advance procurement: project stock",
    "prior_vendor_kolif": "Prior Vendor",
    "vendor_subrange_ltsnr": "Vendor Subrange",
    "package_number_packno": "Package number",
    "invoicing_plan_number_fplnr": "Invoicing plan number",
    "item_is_statistical_stapo": "Item is statistical",
    "higher_level_item_in_purchasing_documents_uebpo": "Higher-Level Item in Purchasing Documents",
    "latest_possible_goods_receipt_lewed": "Latest Possible Goods Receipt",
    "vendor_to_be_supplied_emlif": "Vendor to be supplied/who is to receive delivery",
    "subcontracting_vendor_lblkz": "Subcontracting vendor",
    "cross_plant_configurable_material_satnr": "Cross-Plant Configurable Materia",
    "material_category_attyp": "Material Category",
    "shipping_type_vsart": "Shipping type",
    "location_for_a_physical_handover_of_goods_handoverloc": "Location for a physical handover of goods",
    "kanban_flag_kanba": "Kanban Indicator",
    "number_of_delivery_address_adrn2": "Number of delivery address",
    "internal_object_number_cuobj": "Configuration (internal object number)",
    "evaluated_receipt_settlement_xersy": "Evaluated Receipt Settlement (ERS)",
    "start_date_for_gr_based_settlement_eildt": "Start Date for GR-Based Settlement",
    "last_transmission_drdat": "Date of Last Transmitted Change",
    "time_druhr": "Time of Transmission",
    "sequential_number_drunr": "Next Transmission Number",
    "promotion_aktnr": "Promotion",
    "allocation_table_number_abeln": "Allocation Table",
    "item_number_of_allocation_table_abelp": "Item number of allocation table",
    "number_of_points_anzpu": "Number of Points",
    "points_unit_punei": "Points unit",
    "season_category_saiso": "Season",
    "season_year_saisj": "Season Year",
    "settlement_group2_ebon2": "Settlement Group 2 (Rebate Settlement, Purchasing)",
    "settlement_group3_ebon3": "Settlement Group 3 (Rebate Settlement, Purchasing)",
    "item_relevant_to_subsequent_settlement_ebonf": "Item Relevant to Subsequent (Period-End Rebate) Settlement",
    "material_ledger_activated_at_material_level_mlmaa": "Material ledger activated at material level",
    "minimum_remaining_shelf_life_mhdrz": "Minimum Remaining Shelf Life",
    "rfq_number_anfnr": "RFQ Number",
    "item_number_of_rfq_anfps": "Item Number of RFQ",
    "origin_of_configuration_kzkfg": "Origin of Configuration",
    "quota_arrangement_usage_usequ": "Quota arrangement usage",
    "special_stock_flag_for_physical_stock_transfer_umsok": "Special Stock Indicator for Physical Stock Transfer",
    "purchase_requisition_number_banfn": "Purchase Requisition Number",
    "item_number_of_purchase_requisition_bnfpo": "Item Number of Purchase Requisition",
    "material_type_mtart": "Material Type",
    "subitem_category_uptyp": "Subitem Category, Purchasing Document",
    "subitems_exist_upvor": "Subitems Exist",
    "subtotal1_from_pricing_procedure_for_condition_kzwi1": "Subtotal 1 from pricing procedure for condition",
    "subtotal2_from_pricing_procedure_for_condition_kzwi2": "Subtotal 2 from pricing procedure for condition",
    "subtotal3_from_pricing_procedure_for_condition_kzwi3": "Subtotal 3 from pricing procedure for condition",
    "subtotal4_from_pricing_procedure_for_condition_kzwi4": "Subtotal 4 from pricing procedure for condition",
    "subtotal5_from_pricing_procedure_for_condition_kzwi5": "Subtotal 5 from pricing procedure for condition",
    "subtotal6_from_pricing_procedure_for_condition_kzwi6": "Subtotal 6 from pricing procedure for condition",
    "processing_key_for_subitems_sikgr": "Processing key for sub-items",
    "maximum_cumulative_material_go_ahead_quantity_mfzhi": "Maximum Cumulative Material Go-Ahead Quantity",
    "maximum_cumulative_production_go_ahead_quantity_ffzhi": "Maximum Cumulative Production Go-Ahead Quantity",
    "returns_item_retpo": "Returns Item",
    "relevant_to_allocation_table_aurel": "Relevant to Allocation Table",
    "reason_for_ordering_bsgru": "Reason for Ordering",
    "delivery_type_for_returns_to_vendors_lfret": "Delivery Type for Returns to Vendors",
    "material_freight_group_mfrgr": "Material freight group",
    "material_qualifies_for_discount_in_kind_nrfhg": "Material qualifies for discount in kind",
    "release_creation_profile_abueb": "Release Creation Profile",
    "next_forecast_delivery_schedule_transmission_nlabd": "Next Forecast Delivery Schedule Transmission",
    "next_jit_delivery_schedule_transmission_nfabd": "Next JIT Delivery Schedule Transmission",
    "valuation_of_special_stock_kzbws": "Valuation of Special Stock",
    "flag_item_relevant_to_jit_delivery_schedules_fabkz": "Indicator: Item Relevant to JIT Delivery Schedules",
    "inflation_index_j_1_aindxp": "Inflation Index",
    "inflation_index_date_j_1_aidatep": "Inflation index date",
    "manufacturer_part_profile_mprof": "Manufacturer Part Profile",
    "outward_delivery_completed_flag_eglkz": "'Outward Delivery Completed' Indicator",
    "stock_transfer_kztlf": "Partial Delivery at Item Level (Stock Transfer)",
    "unit_of_measure_usage_kzfme": "Units of measure usage",
    "rounding_profile_rdprf": "Rounding Profile",
    "standard_variant_techs": "Parameter Variant/Standard Variant",
    "configuration_changed_chg_srv": "Configuration changed",
    "no_invoice_for_item_although_not_free_of_charge_chg_fplnr": "No invoice for this item although not free of charge",
    "manufacturer_part_number_mfrpn": "Manufacturer Part Number",
    "number_of_a_manufacturer_mfrnr": "Number of a Manufacturer",
    "external_manufacturer_codename_or_number_emnfr": "External manufacturer code name or number",
    "item_blocked_for_sd_delivery_novet": "Item blocked for SD delivery",
    "name_of_requester_afnam": "Name of Requisitioner/Requester",
    "timezone_of_recipient_location_tzonrc": "Name of Requisitioner/Requester",
    "period_flag_for_shelf_life_expiration_date_iprkz": "Period Indicator for Shelf Life Expiration Date",
    "flag_for_service_based_invoice_verification_lebre": "Indicator for Service-Based Invoice Verification",
    "mrp_area_berid": "MRP Area",
    "conditions_for_item_although_no_invoice_xconditions": "Conditions for item although no invoice",
    "ap_oas_planning_system_apoms": "APO as Planning System",
    "posting_logic_in_the_case_of_stock_transfers_ccomp": "Posting Logic in the Case of Stock Transfers",
    "grant_grant_nbr": "Grant",
    "functional_area_fkber": "Functional Area",
    "status_of_purchasing_document_item_status": "Status of Purchasing Document Item",
    "issuing_storage_location_for_stock_transport_order_reslo": "Issuing Storage Location for Stock Transport Order",
    "document_number_for_earmarked_funds_kblnr": "Document Number for Earmarked Funds",
    "earmarked_funds_document_item_kblpos": "Earmarked Funds: Document Item",
    "acceptance_at_origin_weora": "Acceptance At Origin",
    "service_based_commitment_srv_bas_com": "Service-Based Commitment",
    "requirement_urgency_prio_urg": "Requirement Urgency",
    "requirement_priority_prio_req": "Requirement Priority",
    "receiving_point_empst": "Receiving point",
    "differential_invoicing_diff_invoice": "Differential Invoicing",
    "risk_relevancyin_purchasing_trmrisk_relevant": "Risk Relevancy in Purchasing",
    "reason_for_rejection_of_quotations_and_sales_orders_spe_abgru": "Reason for rejection of quotations and sales orders",
    "crm_sales_order_number_for_tpop_spe_crm_so": "CRM Sales Order Number for TPOP Process",
    "crm_sales_order_item_number_in_tpop_spe_crm_so_item": "CRM Sales Order Item Number in TPOP Process",
    "crm_reference_order_number_for_tpop_spe_crm_ref_so": "CRM Reference Order Number for TPOP Process",
    "crm_reference_sales_order_item_number_in_tpop_spe_crm_ref_item": "CRM Reference Sales Order Item Number in TPOP Process",
    "billing_relevance_crm_spe_crm_fkrel": "Billing Relevance CRM",
    "last_changer_system_type_spe_chng_sys": "Last Changer's System Type",
    "stock_typeof_source_storage_location_in_sto_spe_insmk_src": "Stock Type of Source Storage Location in STO",
    "cq_control_type_spe_cq_ctrltype": "CQ Control Type",
    "no_transmission_of_cumulative_quantities_in_sa_release_spe_cq_nocq": "No Transmission of Cumulative Quantities in SA Release",
    "goods_receipt_reason_code_reason_code": "Goods Receipt Reason Code",
    "cumulative_goods_receipts_cqu_sar": "Cumulative Goods Receipts from Redirected Purchase Orders",
    "number_of_serial_numbers_anzsn": "Number of serial numbers",
    "ewm_delivery_based_tolerance_check_spe_ewm_dtc": "EWM Delivery Based Tolerance Check",
    "item_number_length_exlin": "Item Number Length",
    "external_sorting_exsnr": "External Sort Number",
    "external_hierarchy_category_ehtyp": "External Hierarchy Category",
    "retention_in_percent_retpc": "Retention in Percent",
    "down_payment_flag_dptyp": "Down Payment Indicator",
    "down_payment_percentage_dppct": "Down Payment Percentage",
    "down_payment_in_document_currency_dpamt": "Down Payment Amount in Document Currency",
    "due_date_for_down_payment_dpdat": "Due Date for Down Payment",
    "store_return_with_inbound_and_outbound_delivery_fls_rsto": "Store Return with Inbound and Outbound Delivery",
    "document_number_of_external_document_ext_rfx_number": "Document Number of External Document",
    "item_number_of_external_document_ext_rfx_item": "Item Number of External Document",
    "logical_system_ext_rfx_system": "Logical System",
    "central_contract_srm_contract_id": "Central Contract",
    "central_contract_item_number_srm_contract_itm": "Central Contract Item Number",
    "blocking_reason_id_blk_reason_id": "Blocking Reason - ID",
    "blocking_reason_text_blk_reason_txt": "Blocking Reason - Text",
    "real_time_consumption_posting_of_subcontracting_components_itcons": "Real-Time Consumption Posting of Subcontracting Components",
    "delivery_date_and_quantity_fixed_fixmg": "Delivery Date and Quantity Fixed",
    "flag_for_gi_based_goods_receipt_wabwe": "Indicator for GI-based goods receipt",
    "tax_code_automatically_determined_tc_aut_det": "Tax Code Automatically Determined",
    "manual_tax_code_reason_manual_tc_reason": "Manual Tax Code Reason",
    "tax_incentive_type_fiscal_incentive": "Tax Incentive Type",
    "tax_subject_tax_subject_st": "Tax Subject to Substitui\u00e7\u00e3o Tribut\u00e1ria",
    "incentive_id_fiscal_incentive_id": "Incentive ID",
    "advice_code_advcode": "Advice Code",
    "fm_budget_period_budget_pd": "FM: Budget Period",
    "acceptance_period_excpe": "Acceptance Period",
    "iuid_relevant_iuid_relevant": "IUID-Relevant",
    "retail_price_relevant_mrpind": "Max Retail Price Relevance",
    "reference_site_for_purchasing_refsite": "Reference Site For Purchasing",
    "type_of_subcontracting_serru": "Type of subcontracting",
    "serial_number_profile_sernp": "Serial Number Profile",
    "special_stock_flag_subcontracting_disub_sobkz": "Special stock indicator Subcontracting",
    "wbs_element_disub_pspnr": "Work Breakdown Structure Element (WBS Element)",
    "customer_number_disub_kunnr": "Customer Number",
    "sales_and_distribution_document_number_disub_vbeln": "Sales and Distribution Document Number",
    "item_number_of_the_sd_document_disub_posnr": "Item number of the SD document",
    "owner_of_stock_disub_owner": "Owner of stock",
    "reference_item_for_remaining_qty_cancellation_ref_item": "Reference Item for Remaining Qty Cancellation",
    "origin_profile_source_id": "Origin Profile",
    "keyin_source_system_source_key": "Key in Source System",
    "flag_for_putting_back_from_grouped_po_document_put_back": "Indicator for Putting Back from Grouped PO Document",
    "order_list_item_number_pol_id": "Order List Item Number",
    "purchase_order_for_consignment_cons_order": "Purchase Order for Consignment",
    "net_price_netpr": "Net Price in Purchasing Document (in Document Currency)",
    "net_order_value_in_po_currency_netwr": "Net Order Value in PO Currency",
    "gross_order_value_in_po_currency_brtwr": "Gross order value in PO currency",
    "target_value_for_outline_agreement_in_document_currency_zwert": "Target Value for Outline Agreement in Document Currency",
    "effective_value_of_item_effwr": "Effective value of item",
    "rebate_basis1_bonba": "Rebate basis 1",
    "bq_loaded_at": "BigQuery Loaded At",
    "source_last_updated_at": "Source Last Updated At"
  }
};

const moduleConfig = config.product[moduleContext.moduleId];

const materializationType = tableConfig.materializationType || "incremental";

const currency = require("includes/cortex/currency.js");
const incremental = require("includes/cortex/incremental.js");
const publish_config = require("includes/cortex/publish_config.js");

const publishConfig = publish_config.getPublishConfig(
  materializationType,
  tableConfig,
  moduleConfig,
  [
    "client_mandt",
    "purchasing_document_number_ebeln",
    "item_number_of_purchasing_document_ebelp"
  ]
);

publish("purchasing_document_items", publishConfig).query(
  (ctx) => `
WITH currency_decimal as (
  ${currency.currencyDecimalShift(ctx.ref(moduleConfig.sources.sapModule.datasetId, "tcurx"))}
)
SELECT
  ekpo.mandt as client_mandt,
  ekpo.ebeln as purchasing_document_number_ebeln,
  ekpo.ebelp as item_number_of_purchasing_document_ebelp,
  ekpo.loekz as deletion_flag_loekz,
  ekpo.statu as rfq_status_statu,
  ekpo.aedat as change_date_aedat,
  ekpo.txz01 as short_text_txz01,
  ekpo.matnr as material_number_matnr,
  ekpo.ematn as material_number_ematn,
  ekpo.bukrs as company_code_bukrs,
  ekpo.werks as plant_werks,
  ekpo.lgort as storage_location_lgort,
  ekpo.bednr as requirement_tracking_number_bednr,
  ekpo.matkl as material_group_matkl,
  ekpo.infnr as number_of_purchasing_info_record_infnr,
  ekpo.idnlf as material_number_vendor_idnlf,
  ekpo.ktmng as target_quantity_ktmng,
  ekpo.menge as po_quantity_menge,
  ekpo.meins as uo_m_meins,
  ekpo.bprme as order_price_unit_bprme,
  ekpo.bpumz as order_unit_numerator_bpumz,
  ekpo.bpumn as order_unit_denominator_bpumn,
  ekpo.umrez as numerator_for_conversion_of_order_unit_to_base_unit_umrez,
  ekpo.umren as denominator_for_conversion_of_order_unit_to_base_unit_umren,
  ekpo.peinh as price_unit_peinh,
  ekpo.agdat as deadline_for_submission_of_bid_agdat,
  ekpo.webaz as goods_receipt_processing_time_in_days_webaz,
  ekpo.mwskz as taxcode_mwskz,
  ekpo.bonus as settlement_group1_bonus,
  ekpo.insmk as stock_type_insmk,
  ekpo.spinf as update_info_record_flag_spinf,
  ekpo.prsdr as price_printout_prsdr,
  ekpo.schpr as estimated_price_flag_schpr,
  ekpo.mahnz as number_of_reminders_mahnz,
  ekpo.mahn1 as number_of_days_for_first_reminder_mahn1,
  ekpo.mahn2 as number_of_days_for_second_reminder_mahn2,
  ekpo.mahn3 as number_of_days_for_third_reminder_mahn3,
  ekpo.uebto as overdelivery_tolerance_limit_uebto,
  ekpo.uebtk as unlimited_overdelivery_allowed_uebtk,
  ekpo.untto as underdelivery_tolerance_limit_untto,
  ekpo.bwtar as valuation_type_bwtar,
  ekpo.bwtty as valuation_category_bwtty,
  ekpo.abskz as rejection_flag_abskz,
  ekpo.agmem as internal_comment_on_quotation_agmem,
  ekpo.elikz as delivery_completed_flag_elikz,
  ekpo.erekz as final_invoice_flag_erekz,
  ekpo.pstyp as item_categoryin_purchasing_document_pstyp,
  ekpo.knttp as account_assignment_category_knttp,
  ekpo.kzvbr as consumption_posting_kzvbr,
  ekpo.vrtkz as distribution_flag_for_multiple_account_assignment_vrtkz,
  ekpo.twrkz as partial_invoice_flag_twrkz,
  ekpo.wepos as goods_receipt_flag_wepos,
  ekpo.weunb as goods_receipt_non_valuated_weunb,
  ekpo.repos as invoice_receipt_flag_repos,
  ekpo.webre as flag_gr_based_invoice_verification_webre,
  ekpo.kzabs as order_acknowledgment_requirement_kzabs,
  ekpo.labnr as order_acknowledgment_number_labnr,
  ekpo.konnr as number_of_principal_purchase_agreement_konnr,
  ekpo.ktpnr as item_number_of_principal_purchase_agreement_ktpnr,
  ekpo.abdat as reconciliation_date_for_agreed_cumulative_quantity_abdat,
  ekpo.abftz as agreed_cumulative_quantity_abftz,
  ekpo.etfz1 as firm_zone_etfz1,
  ekpo.etfz2 as trade_off_zone_etfz2,
  ekpo.kzstu as firm_trade_off_zones_kzstu,
  ekpo.notkz as exclusion_in_outline_agreement_item_with_material_class_notkz,
  ekpo.lmein as base_unit_of_measure_lmein,
  ekpo.evers as shipping_instructions_evers,
  ekpo.navnw as non_deductible_input_tax_navnw,
  ekpo.abmng as standard_release_order_quantity_abmng,
  ekpo.prdat as date_of_price_determination_prdat,
  ekpo.bstyp as purchasing_document_category_bstyp,
  ekpo.xoblr as item_affects_commitments_xoblr,
  ekpo.adrnr as manual_address_number_in_purchasing_document_item_adrnr,
  ekpo.ekkol as condition_group_with_vendor_ekkol,
  ekpo.sktof as item_does_not_qualify_for_cash_discount_sktof,
  ekpo.stafo as update_group_for_statistics_update_stafo,
  ekpo.plifz as planned_delivery_time_in_days_plifz,
  ekpo.ntgew as net_weight_ntgew,
  ekpo.gewei as unit_of_weight_gewei,
  ekpo.txjcd as tax_jurisdiction_txjcd,
  ekpo.etdrk as flag_print_relevant_schedule_lines_exist_etdrk,
  ekpo.sobkz as special_stock_flag_sobkz,
  ekpo.arsnr as settlement_reservation_number_arsnr,
  ekpo.arsps as item_number_of_the_settlement_reservation_arsps,
  ekpo.insnc as quality_inspection_flag_cannot_be_changed_insnc,
  ekpo.ssqss as control_key_for_quality_management_in_procurement_ssqss,
  ekpo.zgtyp as certificate_type_zgtyp,
  ekpo.ean11 as international_article_number_ean11,
  ekpo.bstae as confirmation_control_key_bstae,
  ekpo.revlv as revision_level_revlv,
  ekpo.geber as fund_geber,
  ekpo.fistl as funds_center_fistl,
  ekpo.fipos as commitment_item_fipos,
  ekpo.ko_gsber as business_area_reported_to_the_partner_ko_gsber,
  ekpo.ko_pargb as assumed_business_area_of_the_business_partner_ko_pargb,
  ekpo.ko_prctr as profit_center_ko_prctr,
  ekpo.ko_pprctr as partner_profit_center_ko_pprctr,
  ekpo.meprf as pricing_date_control_meprf,
  ekpo.brgew as gross_weight_brgew,
  ekpo.volum as volume_volum,
  ekpo.voleh as volume_unit_voleh,
  ekpo.inco1 as incoterms1_inco1,
  ekpo.inco2 as incoterms2_inco2,
  ekpo.vorab as advance_procurement_vorab,
  ekpo.kolif as prior_vendor_kolif,
  ekpo.ltsnr as vendor_subrange_ltsnr,
  ekpo.packno as package_number_packno,
  ekpo.fplnr as invoicing_plan_number_fplnr,
  ekpo.stapo as item_is_statistical_stapo,
  ekpo.uebpo as higher_level_item_in_purchasing_documents_uebpo,
  ekpo.lewed as latest_possible_goods_receipt_lewed,
  ekpo.emlif as vendor_to_be_supplied_emlif,
  ekpo.lblkz as subcontracting_vendor_lblkz,
  ekpo.satnr as cross_plant_configurable_material_satnr,
  ekpo.attyp as material_category_attyp,
  ekpo.vsart as shipping_type_vsart,
  ekpo.handoverloc as location_for_a_physical_handover_of_goods_handoverloc,
  ekpo.kanba as kanban_flag_kanba,
  ekpo.adrn2 as number_of_delivery_address_adrn2,
  ekpo.cuobj as internal_object_number_cuobj,
  ekpo.xersy as evaluated_receipt_settlement_xersy,
  ekpo.eildt as start_date_for_gr_based_settlement_eildt,
  ekpo.drdat as last_transmission_drdat,
  ekpo.druhr as time_druhr,
  ekpo.drunr as sequential_number_drunr,
  ekpo.aktnr as promotion_aktnr,
  ekpo.abeln as allocation_table_number_abeln,
  ekpo.abelp as item_number_of_allocation_table_abelp,
  ekpo.anzpu as number_of_points_anzpu,
  ekpo.punei as points_unit_punei,
  ekpo.saiso as season_category_saiso,
  ekpo.saisj as season_year_saisj,
  ekpo.ebon2 as settlement_group2_ebon2,
  ekpo.ebon3 as settlement_group3_ebon3,
  ekpo.ebonf as item_relevant_to_subsequent_settlement_ebonf,
  ekpo.mlmaa as material_ledger_activated_at_material_level_mlmaa,
  ekpo.mhdrz as minimum_remaining_shelf_life_mhdrz,
  ekpo.anfnr as rfq_number_anfnr,
  ekpo.anfps as item_number_of_rfq_anfps,
  ekpo.kzkfg as origin_of_configuration_kzkfg,
  ekpo.usequ as quota_arrangement_usage_usequ,
  ekpo.umsok as special_stock_flag_for_physical_stock_transfer_umsok,
  ekpo.banfn as purchase_requisition_number_banfn,
  ekpo.bnfpo as item_number_of_purchase_requisition_bnfpo,
  ekpo.mtart as material_type_mtart,
  ekpo.uptyp as subitem_category_uptyp,
  ekpo.upvor as subitems_exist_upvor,
  ekpo.kzwi1 as subtotal1_from_pricing_procedure_for_condition_kzwi1,
  ekpo.kzwi2 as subtotal2_from_pricing_procedure_for_condition_kzwi2,
  ekpo.kzwi3 as subtotal3_from_pricing_procedure_for_condition_kzwi3,
  ekpo.kzwi4 as subtotal4_from_pricing_procedure_for_condition_kzwi4,
  ekpo.kzwi5 as subtotal5_from_pricing_procedure_for_condition_kzwi5,
  ekpo.kzwi6 as subtotal6_from_pricing_procedure_for_condition_kzwi6,
  ekpo.sikgr as processing_key_for_subitems_sikgr,
  ekpo.mfzhi as maximum_cumulative_material_go_ahead_quantity_mfzhi,
  ekpo.ffzhi as maximum_cumulative_production_go_ahead_quantity_ffzhi,
  ekpo.retpo as returns_item_retpo,
  ekpo.aurel as relevant_to_allocation_table_aurel,
  ekpo.bsgru as reason_for_ordering_bsgru,
  ekpo.lfret as delivery_type_for_returns_to_vendors_lfret,
  ekpo.mfrgr as material_freight_group_mfrgr,
  ekpo.nrfhg as material_qualifies_for_discount_in_kind_nrfhg,
  ekpo.abueb as release_creation_profile_abueb,
  ekpo.nlabd as next_forecast_delivery_schedule_transmission_nlabd,
  ekpo.nfabd as next_jit_delivery_schedule_transmission_nfabd,
  ekpo.kzbws as valuation_of_special_stock_kzbws,
  ekpo.fabkz as flag_item_relevant_to_jit_delivery_schedules_fabkz,
  ekpo.j_1aindxp as inflation_index_j_1_aindxp,
  ekpo.j_1aidatep as inflation_index_date_j_1_aidatep,
  ekpo.mprof as manufacturer_part_profile_mprof,
  ekpo.eglkz as outward_delivery_completed_flag_eglkz,
  ekpo.kztlf as stock_transfer_kztlf,
  ekpo.kzfme as unit_of_measure_usage_kzfme,
  ekpo.rdprf as rounding_profile_rdprf,
  ekpo.techs as standard_variant_techs,
  ekpo.chg_srv as configuration_changed_chg_srv,
  ekpo.chg_fplnr as no_invoice_for_item_although_not_free_of_charge_chg_fplnr,
  ekpo.mfrpn as manufacturer_part_number_mfrpn,
  ekpo.mfrnr as number_of_a_manufacturer_mfrnr,
  ekpo.emnfr as external_manufacturer_codename_or_number_emnfr,
  ekpo.novet as item_blocked_for_sd_delivery_novet,
  ekpo.afnam as name_of_requester_afnam,
  ekpo.tzonrc as timezone_of_recipient_location_tzonrc,
  ekpo.iprkz as period_flag_for_shelf_life_expiration_date_iprkz,
  ekpo.lebre as flag_for_service_based_invoice_verification_lebre,
  ekpo.berid as mrp_area_berid,
  ekpo.xconditions as conditions_for_item_although_no_invoice_xconditions,
  ekpo.apoms as ap_oas_planning_system_apoms,
  ekpo.ccomp as posting_logic_in_the_case_of_stock_transfers_ccomp,
  ekpo.grant_nbr as grant_grant_nbr,
  ekpo.fkber as functional_area_fkber,
  ekpo.status as status_of_purchasing_document_item_status,
  ekpo.reslo as issuing_storage_location_for_stock_transport_order_reslo,
  ekpo.kblnr as document_number_for_earmarked_funds_kblnr,
  ekpo.kblpos as earmarked_funds_document_item_kblpos,
  ekpo.weora as acceptance_at_origin_weora,
  ekpo.srv_bas_com as service_based_commitment_srv_bas_com,
  ekpo.prio_urg as requirement_urgency_prio_urg,
  ekpo.prio_req as requirement_priority_prio_req,
  ekpo.empst as receiving_point_empst,
  ekpo.diff_invoice as differential_invoicing_diff_invoice,
  ekpo.trmrisk_relevant as risk_relevancyin_purchasing_trmrisk_relevant,
  ekpo.spe_abgru as reason_for_rejection_of_quotations_and_sales_orders_spe_abgru,
  ekpo.spe_crm_so as crm_sales_order_number_for_tpop_spe_crm_so,
  ekpo.spe_crm_so_item as crm_sales_order_item_number_in_tpop_spe_crm_so_item,
  ekpo.spe_crm_ref_so as crm_reference_order_number_for_tpop_spe_crm_ref_so,
  ekpo.spe_crm_ref_item as crm_reference_sales_order_item_number_in_tpop_spe_crm_ref_item,
  ekpo.spe_crm_fkrel as billing_relevance_crm_spe_crm_fkrel,
  ekpo.spe_chng_sys as last_changer_system_type_spe_chng_sys,
  ekpo.spe_insmk_src as stock_typeof_source_storage_location_in_sto_spe_insmk_src,
  ekpo.spe_cq_ctrltype as cq_control_type_spe_cq_ctrltype,
  ekpo.spe_cq_nocq as no_transmission_of_cumulative_quantities_in_sa_release_spe_cq_nocq,
  ekpo.reason_code as goods_receipt_reason_code_reason_code,
  ekpo.cqu_sar as cumulative_goods_receipts_cqu_sar,
  ekpo.anzsn as number_of_serial_numbers_anzsn,
  ekpo.spe_ewm_dtc as ewm_delivery_based_tolerance_check_spe_ewm_dtc,
  ekpo.exlin as item_number_length_exlin,
  ekpo.exsnr as external_sorting_exsnr,
  ekpo.ehtyp as external_hierarchy_category_ehtyp,
  ekpo.retpc as retention_in_percent_retpc,
  ekpo.dptyp as down_payment_flag_dptyp,
  ekpo.dppct as down_payment_percentage_dppct,
  ekpo.dpamt as down_payment_in_document_currency_dpamt,
  ekpo.dpdat as due_date_for_down_payment_dpdat,
  ekpo.fls_rsto as store_return_with_inbound_and_outbound_delivery_fls_rsto,
  ekpo.ext_rfx_number as document_number_of_external_document_ext_rfx_number,
  ekpo.ext_rfx_item as item_number_of_external_document_ext_rfx_item,
  ekpo.ext_rfx_system as logical_system_ext_rfx_system,
  ekpo.srm_contract_id as central_contract_srm_contract_id,
  ekpo.srm_contract_itm as central_contract_item_number_srm_contract_itm,
  ekpo.blk_reason_id as blocking_reason_id_blk_reason_id,
  ekpo.blk_reason_txt as blocking_reason_text_blk_reason_txt,
  ekpo.itcons as real_time_consumption_posting_of_subcontracting_components_itcons,
  ekpo.fixmg as delivery_date_and_quantity_fixed_fixmg,
  ekpo.wabwe as flag_for_gi_based_goods_receipt_wabwe,
  ekpo.tc_aut_det as tax_code_automatically_determined_tc_aut_det,
  ekpo.manual_tc_reason as manual_tax_code_reason_manual_tc_reason,
  ekpo.fiscal_incentive as tax_incentive_type_fiscal_incentive,
  ekpo.tax_subject_st as tax_subject_tax_subject_st,
  ekpo.fiscal_incentive_id as incentive_id_fiscal_incentive_id,
  ekpo.advcode as advice_code_advcode,
  ekpo.budget_pd as fm_budget_period_budget_pd,
  ekpo.excpe as acceptance_period_excpe,
  ekpo.iuid_relevant as iuid_relevant_iuid_relevant,
  ekpo.mrpind as retail_price_relevant_mrpind,
  ekpo.refsite as reference_site_for_purchasing_refsite,
  ekpo.serru as type_of_subcontracting_serru,
  ekpo.sernp as serial_number_profile_sernp,
  ekpo.disub_sobkz as special_stock_flag_subcontracting_disub_sobkz,
  ekpo.disub_pspnr as wbs_element_disub_pspnr,
  ekpo.disub_kunnr as customer_number_disub_kunnr,
  ekpo.disub_vbeln as sales_and_distribution_document_number_disub_vbeln,
  ekpo.disub_posnr as item_number_of_the_sd_document_disub_posnr,
  ekpo.disub_owner as owner_of_stock_disub_owner,
  ekpo.ref_item as reference_item_for_remaining_qty_cancellation_ref_item,
  ekpo.source_id as origin_profile_source_id,
  ekpo.source_key as keyin_source_system_source_key,
  ekpo.put_back as flag_for_putting_back_from_grouped_po_document_put_back,
  ekpo.pol_id as order_list_item_number_pol_id,
  ekpo.cons_order as purchase_order_for_consignment_cons_order,
  ekko.waers as currency_key_waers,
  ${currency.amountWithDecimalShift("ekpo.netpr", "currency_decimal")} as net_price_netpr,
  ${currency.amountWithDecimalShift("ekpo.netwr", "currency_decimal")} as net_order_value_in_po_currency_netwr,
  ${currency.amountWithDecimalShift("ekpo.brtwr", "currency_decimal")} as gross_order_value_in_po_currency_brtwr,
  ${currency.amountWithDecimalShift("ekpo.zwert", "currency_decimal")} as target_value_for_outline_agreement_in_document_currency_zwert,
  ${currency.amountWithDecimalShift("ekpo.effwr", "currency_decimal")} as effective_value_of_item_effwr,
  ${currency.amountWithDecimalShift("ekpo.bonba", "currency_decimal")} as rebate_basis1_bonba,
  GREATEST(
    IFNULL(ekpo.recordstamp, TIMESTAMP('1900-01-01 00:00:00+00')),
    IFNULL(ekko.recordstamp, TIMESTAMP('1900-01-01 00:00:00+00'))
  ) as source_last_updated_at,
  CURRENT_TIMESTAMP() as bq_loaded_at
FROM
  ${ctx.ref(moduleConfig.sources.sapModule.datasetId, 'ekpo')} as ekpo
LEFT JOIN
  ${ctx.ref(moduleConfig.sources.sapModule.datasetId, 'ekko')} as ekko
  ON ekpo.mandt = ekko.mandt
  AND ekpo.ebeln = ekko.ebeln
LEFT JOIN currency_decimal
  ON ekko.waers = currency_decimal.currkey
${incremental.getWhere(ctx, ["ekpo.recordstamp", "ekko.recordstamp"])}
`,
);
