/**
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

const moduleContext = {
  "moduleId": "sap_delivery_documents"
};
const tableConfig = {
  "tags": [
    "sap",
    "dataproduct",
    "transactional"
  ],
  "materializationType": "incremental",
  "description": "Information about delivery document items at the granularity of Client(System), Delivery document number and Item number of delivery document.",
  "columns": {
    "client_mandt": "Client (Mandant), PK",
    "document_number_vbeln": "Delivery Document Number, PK",
    "item_number_posnr": "Item Number, PK",
    "item_category_pstyv": "Item Category",
    "created_by_ernam": "Name of the person who created the delivery document item",
    "creation_time_erzet": "Time of creation (Entry time) of the delivery document item",
    "creation_date_erdat": "Date of creation of the delivery document item",
    "material_number_matnr": "Material Number",
    "material_entered_matwa": "Material Entered",
    "material_group_matkl": "Material Group",
    "plant_werks": "Plant",
    "storage_location_lgort": "Storage Location",
    "batch_number_charg": "Batch Number",
    "vendor_batch_number_lichn": "Vendor Batch Number",
    "material_belonging_to_the_customer_kdmat": "Material Belonging to the Customer",
    "product_hierarchy_prodh": "Product Hierarchy",
    "actual_quantity_delivered_in_sales_units_lfimg": "Actual Quantity Delivered in Sales Units",
    "base_unit_of_measure_meins": "Base Unit of Measure",
    "sales_unit_vrkme": "Sales Unit",
    "numerator_factor_for_conversion_of_sales_quantity_into_sku_umvkz": "Numerator Factor for Conversion of Sales Quantity into SKU",
    "denominator_divisor_for_conversion_of_sales_qty_into_sku_umvkn": "Denominator Divisor for Conversion of Sales Qty into SKU",
    "net_weight_ntgew": "Net Weight",
    "gross_weight_brgew": "Gross Weight",
    "weight_unit_gewei": "Weight Unit",
    "volume_volum": "Volume",
    "volume_unit_voleh": "Volume Unit",
    "partial_delivery_at_item_level_kztlf": "Partial Delivery at Item Level",
    "indicator_unlimited_overdelivery_allowed_uebtk": "Indicator: Unlimited Overdelivery Allowed",
    "overdelivery_tolerance_limit_uebto": "Overdelivery Tolerance Limit",
    "underdelivery_tolerance_limit_untto": "Underdelivery Tolerance Limit",
    "batch_split_allowed_chspl": "Batch Split Allowed",
    "billing_block_faksp": "Billing Block",
    "material_availability_date_mbdat": "Material Availability Date",
    "actual_quantity_delivered_in_stock_keeping_units_lgmng": "Actual Quantity Delivered in Stock Keeping Units",
    "short_text_for_sales_order_item_arktx": "Short Text for Sales Order Item",
    "storage_bin_lgpbe": "Storage Bin",
    "originating_document_vbelv": "Originating Document",
    "originating_item_posnv": "Originating Item",
    "sd_document_category_vbtyv": "SD Document Category",
    "logical_system_in_the_preceding_document_vgsys": "Logical System in the Preceding Document",
    "internal_reference_document_number_vgbel": "Internal Reference Document Number",
    "internal_reference_document_item_vgpos": "Internal Reference Document Item",
    "update_indicator_for_delivery_document_flow_upflu": "Update Indicator for Delivery Document Flow",
    "higher_level_item_in_bom_uepos": "Higher Level Item in BOM",
    "relevant_for_billing_fkrel": "Relevant for Billing",
    "loading_group_ladgr": "Loading Group",
    "transportation_group_tragr": "Transportation Group",
    "indicator_for_picking_control_komkz": "Indicator for Picking Control",
    "warehouse_number_lgnum": "Warehouse Number",
    "split_to_warehouse_number_required_lispl": "Split to Warehouse Number Required",
    "storage_type_lgtyp": "Storage Type",
    "storage_bin_lgpla": "Storage Bin",
    "indicator_separate_valuation_bwtex": "Indicator: Separate Valuation",
    "movement_type_inventory_management_bwart": "Movement Type (Inventory Management)",
    "movement_type_for_warehouse_management_bwlvs": "Movement Type for Warehouse Management",
    "indicator_dynamic_storage_bin_in_warehouse_management_kzdlg": "Indicator: Dynamic Storage Bin in Warehouse Management",
    "requirement_type_bdart": "Requirement Type",
    "planning_type_plart": "Planning Type",
    "material_type_mtart": "Material Type",
    "batch_management_requirement_indicator_xchpf": "Batch Management Requirement Indicator",
    "batch_management_indicator_internal_xchar": "Batch Management Indicator (Internal)",
    "preceding_document_has_resulted_from_reference_vgref": "Preceding Document Has Resulted From Reference",
    "item_type_posar": "Item Type",
    "valuation_type_bwtar": "Valuation Type",
    "summing_up_of_requirements_sumbd": "Summing Up of Requirements",
    "checking_group_for_availability_mtvfp": "Checking Group for Availability",
    "european_article_number_eannr": "European Article Number",
    "business_area_gsber": "Business Area",
    "sales_office_vkbur": "Sales Office",
    "sales_group_vkgrp": "Sales Group",
    "distribution_channel_vtweg": "Distribution Channel",
    "division_spart": "Division",
    "delivery_group_items_are_delivered_together_grkor": "Delivery Group Items Are Delivered Together",
    "quantity_is_fixed_fmeng": "Quantity Is Fixed",
    "maximum_number_of_partial_deliveries_allowed_per_item_antlf": "Maximum Number of Partial Deliveries Allowed Per Item",
    "fixed_shipping_processing_time_in_days_vbeaf": "Fixed Shipping Processing Time in Days",
    "variable_shipping_processing_time_in_days_vbeav": "Variable Shipping Processing Time in Days",
    "update_group_for_statistics_update_stafo": "Update Group for Statistics Update",
    "cost_in_document_currency_wavwr": "Cost in Document Currency",
    "subtotal1_from_pricing_procedure_for_condition_kzwi1": "Subtotal1 From Pricing Procedure For Condition",
    "subtotal2_from_pricing_procedure_for_condition_kzwi2": "Subtotal2 From Pricing Procedure For Condition",
    "subtotal3_from_pricing_procedure_for_condition_kzwi3": "Subtotal3 From Pricing Procedure For Condition",
    "subtotal4_from_pricing_procedure_for_condition_kzwi4": "Subtotal4 From Pricing Procedure For Condition",
    "subtotal5_from_pricing_procedure_for_condition_kzwi5": "Subtotal5 From Pricing Procedure For Condition",
    "subtotal6_from_pricing_procedure_for_condition_kzwi6": "Subtotal6 From Pricing Procedure For Condition",
    "special_stock_indicator_sobkz": "Special Stock Indicator",
    "changed_on_aedat": "Changed On",
    "international_article_number_eanupc_ean11": "International Article Number (EAN/UPC)",
    "customer_group1_kvgr1": "Customer Group 1",
    "customer_group2_kvgr2": "Customer Group 2",
    "customer_group3_kvgr3": "Customer Group 3",
    "customer_group4_kvgr4": "Customer Group 4",
    "customer_group5_kvgr5": "Customer Group 5",
    "material_group1_mvgr1": "Material Group 1",
    "material_group2_mvgr2": "Material Group 2",
    "material_group3_mvgr3": "Material Group 3",
    "material_group4_mvgr4": "Material Group 4",
    "material_group5_mvgr5": "Material Group 5",
    "allocation_indicator_vpzuo": "Allocation Indicator",
    "sd_document_category_vgtyp": "SD Document Category",
    "type_of_preceding_document_in_central_system_rfvgtyp": "Type of Preceding Document in Central System",
    "cost_center_kostl": "Cost Center",
    "controlling_area_kokrs": "Controlling Area",
    "profitability_segment_number_paobjnr": "Profitability Segment Number",
    "profit_center_prctr": "Profit Center",
    "work_breakdown_structure_element_wbs_element_ps_psp_pnr": "Work Breakdown Structure Element (WBS Element)",
    "order_number_aufnr": "Order Number",
    "order_item_number_posnr_pp": "Order Item Number",
    "sales_order_number_kdauf": "Sales Order Number",
    "item_number_in_sales_order_kdpos": "Item Number in Sales Order",
    "planning_material_vpmat": "Planning Material",
    "planning_plant_vpwrk": "Planning Plant",
    "base_unit_of_measure_for_product_group_prbme": "Base Unit of Measure for Product Group",
    "conversion_factor_quantities_umref": "Conversion Factor Quantities",
    "account_assignment_category_knttp": "Account Assignment Category",
    "consumption_posting_kzvbr": "Consumption Posting",
    "commitment_item_fipos": "Commitment Item",
    "funds_center_fistl": "Funds Center",
    "fund_geber": "Fund",
    "packing_control_pckpf": "Packing Control",
    "requirements_class_bedar_lf": "Requirements Class",
    "id_item_with_active_credit_function_relevant_for_credit_cmpnt": "Item With Active Credit Function Relevant For Credit Cmpnt",
    "cumulative_batch_quantity_of_all_split_items_in_stckunit_kcmeng": "Cumulative Batch Quantity Of All Split Items In Stckunit",
    "cumulative_gross_weight_of_all_batch_split_items_kcbrgew": "Cumulative Gross Weight Of All Batch Split Items",
    "cumulative_net_weight_of_all_batch_split_items_kcntgew": "Cumulative Net Weight Of All Batch Split Items",
    "cumulative_volume_of_all_batch_split_items_kcvolum": "Cumulative Volume Of All Batch Split Items",
    "higher_level_item_of_batch_split_item_uecha": "Higher Level Item Of Batch Split Item",
    "configuration_cuobj": "Configuration",
    "internal_object_number_of_the_batch_classification_cuobj_ch": "Internal Object Number Of The Batch Classification",
    "number_of_serial_numbers_anzsn": "Number Of Serial Numbers",
    "serial_number_profile_serail": "Serial Number Profile",
    "weight_unit_kcgewei": "Weight Unit",
    "volume_unit_kcvoleh": "Volume Unit",
    "bom_explosion_number_sernr": "Bom Explosion Number",
    "internal_delivery_schedule_number_abrli": "Internal Delivery Schedule Number",
    "rel_type_abart": "Rel Type",
    "usage_indicator_abrvw": "Usage Indicator",
    "inspection_lot_number_qplos": "Inspection Lot Number",
    "partial_lot_number_qtlos": "Partial Lot Number",
    "customer_has_not_posted_goods_receipt_nachl": "Customer Has Not Posted Goods Receipt",
    "material_group_packaging_materials_magrv": "Material Group Packaging Materials",
    "object_number_at_header_level_objko": "Object Number At Header Level",
    "object_number_at_item_level_objpo": "Object Number At Item Level",
    "customer_engineering_change_status_aeskd": "Customer Engineering Change Status",
    "returns_item_shkzg": "Returns Item",
    "id_for_material_determination_prosa": "Id For Material Determination",
    "higher_level_item_usage_uepvw": "Higher Level Item Usage",
    "receiving_point_empst": "Receiving Point",
    "department_number_abtnr": "Department Number",
    "picking_is_subject_to_confirmation_koqui": "Picking Is Subject To Confirmation",
    "statistics_date_stadat": "Statistics Date",
    "promotion_aktnr": "Promotion",
    "number_of_condition_record_from_batch_determination_knumh_ch": "Number Of Condition Record From Batch Determination",
    "preference_indicator_in_exportimport_prefe": "Preference Indicator In Exportimport",
    "business_transaction_type_for_foreign_trade_exart": "Business Transaction Type For Foreign Trade",
    "internal_class_number_clint": "Internal Class Number",
    "batches_exit_to_quantity_proposal_chmvs": "Batches Exit To Quantity Proposal",
    "allocation_table_number_abeln": "Allocation Table Number",
    "item_number_of_allocation_table_abelp": "Item Number Of Allocation Table",
    "internal_field_do_not_use_lfimg_in_float_mum_lfimg_flo": "Internal Field Do Not Use Lfimg In Float Mum",
    "internal_field_do_not_use_lgmng_in_float_mum_lgmng_flo": "Internal Field Do Not Use Lgmng In Float Mum",
    "internal_field_do_not_use_kcmeng_in_float_mum_kcmeng_flo": "Internal Field Do Not Use Kcmeng In Float Mum",
    "environmentally_relevant_kzumw": "Environmentally Relevant",
    "component_quantity_kmpmg": "Component Quantity",
    "relevant_to_allocation_table_aurel": "Relevant To Allocation Table",
    "condition_pricing_unit_kpein": "Condition Pricing Unit",
    "condition_unit_kmein": "Condition Unit",
    "net_price_netpr": "Net Price",
    "net_value_in_document_currency_netwr": "Net Value in Document Currency",
    "movement_indicator_kzbew": "Movement Indicator",
    "material_freight_group_mfrgr": "Material Freight Group",
    "pack_accumulated_batches_movement_type_item_chhpv": "Pack Accumulated Batches Movement Type Item",
    "form_of_payment_guarantee_abfor": "Form Of Payment Guarantee",
    "guaranteed_factor_between0_and1_abges": "Guaranteed Factor Between0 And1",
    "material_staging_time_mbuhr": "Material Staging Time",
    "value_contract_no_wktnr": "Value Contract No",
    "value_contract_item_wktps": "Value Contract Item",
    "cfop_code_and_extension_j_1_bcfop": "CFOP Code And Extension",
    "tax_law_icms_j_1_btaxlw1": "Tax Law ICMS",
    "tax_law_ipi_j_1_btaxlw2": "Tax Law IPI",
    "sd_tax_code_j_1_btxsdc": "SD Tax Code",
    "indicator_for_situation_situa": "Indicator For Situation",
    "number_of_reservationdependent_requirements_rsnum": "Number Of ReservationDependent Requirements",
    "item_number_of_reservation_dependent_requirements_rspos": "Item Number Of Reservation Dependent Requirements",
    "record_type_rsart": "Record Type",
    "kanbansequence_number_kannr": "Kanbansequence Number",
    "id_leading_unit_of_measure_for_completing_a_transaction_kzfme": "Id Leading Unit Of Measure For Completing A Transaction",
    "dangerous_goods_indicator_profile_profl": "Dangerous Goods Indicator Profile",
    "cumulative_batch_quantity_of_all_split_items_in_sales_units_kcmengvme": "Cumulative Batch Quantity Of All Split Items In Sales Units",
    "cumulated_batch_split_quantity_in_vrkme_and_float_kcmengvmef": "Cumulated Batch Split Quantity In Vrkme And Float",
    "valuation_of_special_stock_kzbws": "Valuation Of Special Stock",
    "project_definition_internal_pspnr": "Project Definition Internal",
    "withdrawal_sequence_group_for_stocks_eprio": "Withdrawal Sequence Group For Stocks",
    "stock_determination_rule_rules": "Stock Determination Rule",
    "indicator_inventory_management_active_kzbef": "Indicator Inventory Management Active",
    "mfr_part_profile_mprof": "Mfr Part Profile",
    "material_number_corresponding_to_manufacturer_part_number_ematn": "Material Number Corresponding To Manufacturer Part Number",
    "staging_area_for_warehouse_complex_lgbzo": "Staging Area For Warehouse Complex",
    "worldwide_unique_key_forlips_handle": "Worldwide Unique Key For Lips Handle",
    "distribution_delivery_original_item_verurpos": "Distribution Delivery Original Item",
    "external_item_number_lifexpos": "External Item Number",
    "indicator_deactivate_availability_check_noatp": "Indicator Deactivate Availability Check",
    "indicator_not_relevant_for_picking_nopck": "Indicator Not Relevant For Picking",
    "reference_movement_type_for_wm_from_material_movements_rblvs": "Reference Movement Type For Wm From Material Movements",
    "mrp_area_berid": "Mrp Area",
    "stock_category_in_the_warehouse_management_system_bestq": "Stock Category In The Warehouse Management System",
    "stock_category_in_the_warehouse_management_system_umbsq": "Stock Category In The Warehouse Management System",
    "receiving_issuing_material_ummat": "Receiving Issuing Material",
    "receiving_plant_issuing_plant_umwrk": "Receiving Plant Issuing Plant",
    "receiving_issuing_storage_location_umlgo": "Receiving Issuing Storage Location",
    "receiving_issuing_batch_umcha": "Receiving Issuing Batch",
    "valuation_type_of_transfer_batch_umbar": "Valuation Type Of Transfer Batch",
    "special_stock_indicator_for_physical_stock_transfer_umsok": "Special Stock Indicator For Physical Stock Transfer",
    "special_stock_number_sonum": "Special Stock Number",
    "special_stock_number_usonu": "Special Stock Number",
    "exchange_rate_for_letter_foreign_trade_akkur": "Exchange Rate For Letter Foreign Trade",
    "current_qty_field_for_arithmetic_operations_akmng": "Current Qty Field For Arithmetic Operations",
    "repair_processing_classification_of_items_vkgru": "Repair Processing Classification Of Items",
    "indicator_unmat_in_main_posting_shkzg_um": "Indicator Unmat In MainPosting",
    "stock_type_insmk": "Stock Type",
    "determination_of_batch_entry_in_the_productionprocess_order_kzech": "Determination Of Batch Entry In The Productionprocess Order",
    "dest_storage_data_from_preceding_document_flgwm": "Dest Storage Data From Preceding Document",
    "material_staging_indicator_for_production_supply_berkz": "Material Staging Indicator For Production Supply",
    "indicator_delivery_item_is_a_hu_item_hupos": "Indicator Delivery Item Is A Hu Item",
    "indicator_item_not_relevant_for_goods_movements_nowab": "Indicator Item Not Relevant For Goods Movements",
    "gl_account_number_konto": "Gl Account Number",
    "final_issue_for_this_reservation_kzear": "Final Issue For This Reservation",
    "date_of_manufacture_hsdat": "Date Of Manufacture",
    "best_before_date_vfdat": "Best Before Date",
    "fiscal_year_of_current_period_lfgja": "Fiscal Year Of Current Period",
    "a_reference_document_lfbnr": "A Reference Document",
    "item_of_a_reference_document_lfpos": "Item Of A Reference Document",
    "reason_for_goods_movment_grund": "Reason For Goods Movment",
    "subsequent_movement_type_fobwa": "Subsequent Movement Type",
    "delivery_category_dlvtp": "Delivery Category",
    "externally_entered_posting_amount_in_local_currency_exbwr": "Externally Entered Posting Amount In Local Currency",
    "quantity_in_purchase_order_price_unit_bpmng": "Quantity In Purchase Order Price Unit",
    "externally_entered_sales_value_in_local_currency_exvkw": "Externally Entered Sales Value In Local Currency",
    "item_credit_price_cmpre_flt": "Item Credit Price",
    "pod_indicator_kzpod": "Pod Indicator",
    "not_relevant_for_distribution_for_wms_lfdez": "Not Relevant For Distribution For Wms",
    "conversion_factor_of_delivery_quantity_vrkme_for_meins_umrev": "Conversion Factor Of Delivery Quantity Vrkme For Meins",
    "pod_control_proof_of_delivery_podrel": "Pod Control Proof Of Delivery",
    "stock_transfertransfer_posting_kzuml": "Stock Transfertransfer Posting",
    "functional_area_fkber": "Functional Area",
    "grant_grant_nbr": "Grant Grant Number",
    "units_of_measure_usage_kzwso": "Units Of Measure Usage",
    "goods_movement_control_gmcontrol": "Goods Movement Control",
    "goods_movement_control_hu_posting_change": "Goods Movement Control Hu Posting Change",
    "receivingissuing_wbs_element_um_ps_psp_pnr": "Receiving Issuing Wbs Element",
    "sequential_number_of_vendor_confirmation_pre_vl_etens": "Sequential Number Of Vendor Confirmation",
    "delivery_completed_spe_gen_elikz": "Delivery Completed Spe Gen Elikz",
    "scrap_indicator_for_ewm_processing_spe_scrap_ind": "Scrap Indicator For Ewm Processing",
    "return_material_authorization_number_spe_auth_number": "Return Material Authorization Number",
    "inspections_inspection_outcome_guid_set_by_ewm_spe_inspout_guid": "Inspections Inspection Outcome Guid Set By Ewm",
    "default_follow_spe_follow_up": "Default Follow Spe Follow Up",
    "end_date_of_validity_period_of_returns_delivery_spe_exp_date_ext": "End Date Of Validity Period Of Returns Delivery",
    "end_date_of_internal_validity_period_of_returns_delivery_spe_exp_date_int": "End Date Of Internal Validity Period Of Returns Delivery",
    "rma_completion_indicator_spe_auth_complet": "Rma Completion Indicator",
    "original_quantity_of_delivery_item_ormng": "Original Quantity Of Delivery Item",
    "atp_time_stamp_spe_atp_tmstmp": "Atp Time Stamp",
    "original_system_type_itm_spe_orig_sys": "Original System Type Itm",
    "cumulative_qty_for_schedagr_vendor_pov_spe_lieffz": "Cumulative Qty For Schedagr Vendor Pov",
    "inbound_delivery_item_has_statusin_plant_spe_imwrk": "Inbound Delivery Item Has Statusin Plant",
    "external_item_identifier_spe_lifexpos2": "External Item Identifier",
    "exception_code_warehouse_for_quantity_difference_spe_except_code": "Exception Code Warehouse For Quantity Difference",
    "retention_quantity_for_scrap_spe_keep_qty": "Retention Quantity For Scrap",
    "alternate_product_number_spe_alternate": "Alternate Product Number",
    "reason_for_material_substitution_spe_mat_subst": "Reason For Material Substitution",
    "structure_of_items_that_are_delivered_together_spe_struc": "Structure Of Items That Are Delivered Together",
    "numerator_of_quotient_for_unit_of_measure_conversion_spe_apo_qntyfac": "Numerator Of Quotient For Unit Of Measure Conversion",
    "denominator_of_quotient_for_unit_of_measure_conversion_spe_apo_qntydiv": "Denominator Of Quotient For Unit Of Measure Conversion",
    "non_preferential_origin_spe_herkl": "Non Preferential Origin",
    "begin_date_of_validity_period_of_returns_delivery_spe_bxp_date_ext": "Begin Date Of Validity Period Of Returns Delivery",
    "delivery_version_at_confirmation_spe_version": "Delivery Version At Confirmation",
    "completion_of_goods_movements_after_difference_postings_spe_compl_mvt": "Completion Of Goods Movements After Difference Postings",
    "cofins_tax_law_j_1_btaxlw4": "Cofins Tax Law",
    "pis_tax_law_j_1_btaxlw5": "Pis Tax Law",
    "iss_tax_law_j_1_btaxlw3": "Iss Tax Law",
    "fm_budget_period_budget_pd": "Budget Period",
    "kanban_indicator_kbnkz": "Kanban Indicator",
    "specification_for_issuing_valuated_stock_in_transit_sitkz": "Specification For Issuing Valuated Stock In Transit",
    "purchase_order_for_consignment_cons_order": "Purchase Order For Consignment",
    "routing_number_for_operations_aufpl": "Routing number for operations",
    "counter_aplzl": "Counter",
    "revenue_accounting_type_farr_reltype": "Rev. Accounting Type",
    "requirement_segment_sgt_rcat": "Requirement Segment",
    "stock_segment_sgt_scat": "Stock Segment",
    "delivery_item_resource_id_resource_id": "Resource ID",
    "loading_unloading_point_loading_point": "Loading/Unloading Point",
    "solution_order_id": "Order",
    "item_number_in_document_solution_order_itm_id": "Item Number in Document",
    "region_of_origin_spe_herkr": "Region of Origin",
    "commodity_code_itm_comco": "Commodity Code",
    "item_status_besta": "Item Status",
    "credit_management_item_status_cmppi": "Credit management: Item status",
    "credit_management_payment_card_status_cmppj": "Credit management: Item status for payment cards",
    "intercompany_billing_status_fkivp": "Intercompany Billing Status",
    "delivery_related_billing_status_fksta": "Delivery Related Billing Status",
    "sd_process_status_gbsta": "SD Process Status",
    "delivery_item_not_complete_hdall": "Delivery Item Not Complete",
    "picking_confirmation_status_koqua": "Picking/Putaway Confirmation",
    "picking_status_kosta": "Picking Status",
    "warehouse_activity_status_lvsta": "Warehouse Activity Status",
    "proof_of_delivery_status_pdsta": "Proof of Delivery Status",
    "packing_status_pksta": "Packing Status",
    "item_general_incompletion_status_uvall": "Item General Incompletion Status",
    "item_billing_incompletion_status_uvfak": "Item Billing Incompletion Status",
    "item_packing_incompletion_status_uvpak": "Item Packing Incompletion Status",
    "item_picking_incompletion_status_uvpik": "Item Picking Incompletion Status",
    "item_delivery_incompletion_status_uvvlk": "Item Delivery Incompletion Status",
    "item_goods_movement_incompletion_status_uvwak": "Item Goods Movement Incompletion Status",
    "distribution_status_vlstp": "Distribution Status",
    "goods_movement_status_wbsta": "Goods Movement Status",
    "incompletion_status_1_uvp01": "Incompletion Status 1",
    "incompletion_status_2_uvp02": "Incompletion Status 2",
    "incompletion_status_3_uvp03": "Incompletion Status 3",
    "incompletion_status_4_uvp04": "Incompletion Status 4",
    "incompletion_status_5_uvp05": "Incompletion Status 5",
    "trade_compliance_embargo_status_emcst": "Trade Compliance Embargo Status",
    "trade_compliance_sanctioned_list_check_status_slcst": "Trade Compliance Sanctioned List Check Status",
    "trade_compliance_legal_control_status_lccst": "Trade Compliance Legal Control Status",
    "chemical_compliance_status_pcsta": "Chemical Compliance Status",
    "dangerous_goods_status_dgsta": "Dangerous Goods Status",
    "safety_data_sheet_status_sdssta": "Safety Data Sheet Status",
    "dtuc_status_sapmp_lbasp": "DTUC Status",
    "eu_delivery_item_arc_status_arc_status": "EU Delivery Item ARC Status",
    "delivery_quantity_parallel_unit_of_measure_cwm_lfimg": "Delivery Quantity PUoM",
    "cwm_delivery_unit_cwm_lfime": "CWM Delivery Unit",
    "picked_quantity_parallel_unit_of_measure_cwm_pikmg": "Picked Qty PUoM",
    "parallel_unit_of_measure_picked_quantity_cwm_pikme": "PUoM PkQty",
    "parallel_quantity_entered_cwm_xenter": "PQ Entered",
    "transfer_order_cwm_xtaenter": "TO",
    "accumulated_cw_batch_quantity_cwm_kcmeng": "Cumultd CW Batch Qty",
    "quantity_to_be_posted_parallel_unit_of_measure_cwm_ebumg": "Qty to Be Posted in PUoM",
    "dummy_delivery_item_dummy_delitm_incl_eew_ps": "Dummy function",
    "inverted_kjedm_inverted": "Inverted",
    "dtuc_sapmp_lba_no": "DTUC",
    "provisional_conversion_factors_sapmp_alt_conv": "Prov. Conversion Factors",
    "door_lgtor": "Door",
    "year_of_creation_date_erdat": "Year Of Creation Date",
    "month_of_creation_date_erdat": "Month Of Creation Date",
    "week_of_creation_date_erdat": "Week Of Creation Date",
    "day_of_month_of_creation_date_erdat": "Day Of Month Of Creation Date",
    "quarter_of_creation_date_erdat": "Quarter Of Creation Date",
    "source_last_updated_at": "Source Last Updated At",
    "bq_loaded_at": "Bq Loaded At"
  }
};

const moduleConfig = config.product[moduleContext.moduleId];

const materializationType = tableConfig.materializationType || "incremental";

const currency = require("includes/cortex/currency.js");
const date = require("includes/cortex/date.js");
const incremental = require("includes/cortex/incremental.js");
const publish_config = require("includes/cortex/publish_config.js");

const publishConfig = publish_config.getPublishConfig(
  materializationType,
  tableConfig,
  moduleConfig,
  [
    "client_mandt",
    "document_number_vbeln",
    "item_number_posnr"
  ]
);

publish("delivery_document_items", publishConfig).query(
  (ctx) => `
WITH date_dimension AS (
  ${date.getDateDimension()}
), currency_decimal as (
  ${currency.currencyDecimalShift(ctx.ref(moduleConfig.sources.sapModule.datasetId, "tcurx"))}
)
SELECT
  lips.mandt AS client_mandt,
  lips.vbeln AS document_number_vbeln,
  lips.posnr AS item_number_posnr,
  lips.pstyv AS item_category_pstyv,
  lips.ernam AS created_by_ernam,
  lips.erzet AS creation_time_erzet,
  lips.erdat AS creation_date_erdat,
  lips.matnr AS material_number_matnr,
  lips.matwa AS material_entered_matwa,
  lips.matkl AS material_group_matkl,
  lips.werks AS plant_werks,
  lips.lgort AS storage_location_lgort,
  lips.charg AS batch_number_charg,
  lips.lichn AS vendor_batch_number_lichn,
  lips.kdmat AS material_belonging_to_the_customer_kdmat,
  lips.prodh AS product_hierarchy_prodh,
  lips.lfimg AS actual_quantity_delivered_in_sales_units_lfimg,
  lips.meins AS base_unit_of_measure_meins,
  lips.vrkme AS sales_unit_vrkme,
  lips.umvkz AS numerator_factor_for_conversion_of_sales_quantity_into_sku_umvkz,
  lips.umvkn AS denominator_divisor_for_conversion_of_sales_qty_into_sku_umvkn,
  lips.ntgew AS net_weight_ntgew,
  lips.brgew AS gross_weight_brgew,
  lips.gewei AS weight_unit_gewei,
  lips.volum AS volume_volum,
  lips.voleh AS volume_unit_voleh,
  lips.kztlf AS partial_delivery_at_item_level_kztlf,
  lips.uebtk AS indicator_unlimited_overdelivery_allowed_uebtk,
  lips.uebto AS overdelivery_tolerance_limit_uebto,
  lips.untto AS underdelivery_tolerance_limit_untto,
  lips.chspl AS batch_split_allowed_chspl,
  lips.faksp AS billing_block_faksp,
  lips.mbdat AS material_availability_date_mbdat,
  lips.lgmng AS actual_quantity_delivered_in_stock_keeping_units_lgmng,
  lips.arktx AS short_text_for_sales_order_item_arktx,
  lips.lgpbe AS storage_bin_lgpbe,
  lips.vbelv AS originating_document_vbelv,
  lips.posnv AS originating_item_posnv,
  lips.vbtyv AS sd_document_category_vbtyv,
  lips.vgsys AS logical_system_in_the_preceding_document_vgsys,
  lips.vgbel AS internal_reference_document_number_vgbel,
  lips.vgpos AS internal_reference_document_item_vgpos,
  lips.upflu AS update_indicator_for_delivery_document_flow_upflu,
  lips.uepos AS higher_level_item_in_bom_uepos,
  lips.fkrel AS relevant_for_billing_fkrel,
  lips.ladgr AS loading_group_ladgr,
  lips.tragr AS transportation_group_tragr,
  lips.komkz AS indicator_for_picking_control_komkz,
  lips.lgnum AS warehouse_number_lgnum,
  lips.lispl AS split_to_warehouse_number_required_lispl,
  lips.lgtyp AS storage_type_lgtyp,
  lips.lgpla AS storage_bin_lgpla,
  lips.bwtex AS indicator_separate_valuation_bwtex,
  lips.bwart AS movement_type_inventory_management_bwart,
  lips.bwlvs AS movement_type_for_warehouse_management_bwlvs,
  lips.kzdlg AS indicator_dynamic_storage_bin_in_warehouse_management_kzdlg,
  lips.bdart AS requirement_type_bdart,
  lips.plart AS planning_type_plart,
  lips.mtart AS material_type_mtart,
  lips.xchpf AS batch_management_requirement_indicator_xchpf,
  lips.xchar AS batch_management_indicator_internal_xchar,
  lips.vgref AS preceding_document_has_resulted_from_reference_vgref,
  lips.posar AS item_type_posar,
  lips.bwtar AS valuation_type_bwtar,
  lips.sumbd AS summing_up_of_requirements_sumbd,
  lips.mtvfp AS checking_group_for_availability_mtvfp,
  lips.eannr AS european_article_number_eannr,
  lips.gsber AS business_area_gsber,
  lips.vkbur AS sales_office_vkbur,
  lips.vkgrp AS sales_group_vkgrp,
  lips.vtweg AS distribution_channel_vtweg,
  lips.spart AS division_spart,
  lips.grkor AS delivery_group_items_are_delivered_together_grkor,
  lips.fmeng AS quantity_is_fixed_fmeng,
  lips.antlf AS maximum_number_of_partial_deliveries_allowed_per_item_antlf,
  lips.vbeaf AS fixed_shipping_processing_time_in_days_vbeaf,
  lips.vbeav AS variable_shipping_processing_time_in_days_vbeav,
  lips.stafo AS update_group_for_statistics_update_stafo,
  ${currency.amountWithDecimalShift("lips.wavwr", "currency_decimal")} AS cost_in_document_currency_wavwr,
  ${currency.amountWithDecimalShift("lips.kzwi1", "currency_decimal")} AS subtotal1_from_pricing_procedure_for_condition_kzwi1,
  ${currency.amountWithDecimalShift("lips.kzwi2", "currency_decimal")} AS subtotal2_from_pricing_procedure_for_condition_kzwi2,
  ${currency.amountWithDecimalShift("lips.kzwi3", "currency_decimal")} AS subtotal3_from_pricing_procedure_for_condition_kzwi3,
  ${currency.amountWithDecimalShift("lips.kzwi4", "currency_decimal")} AS subtotal4_from_pricing_procedure_for_condition_kzwi4,
  ${currency.amountWithDecimalShift("lips.kzwi5", "currency_decimal")} AS subtotal5_from_pricing_procedure_for_condition_kzwi5,
  ${currency.amountWithDecimalShift("lips.kzwi6", "currency_decimal")} AS subtotal6_from_pricing_procedure_for_condition_kzwi6,
  lips.sobkz AS special_stock_indicator_sobkz,
  lips.aedat AS changed_on_aedat,
  lips.ean11 AS international_article_number_eanupc_ean11,
  lips.kvgr1 AS customer_group1_kvgr1,
  lips.kvgr2 AS customer_group2_kvgr2,
  lips.kvgr3 AS customer_group3_kvgr3,
  lips.kvgr4 AS customer_group4_kvgr4,
  lips.kvgr5 AS customer_group5_kvgr5,
  lips.mvgr1 AS material_group1_mvgr1,
  lips.mvgr2 AS material_group2_mvgr2,
  lips.mvgr3 AS material_group3_mvgr3,
  lips.mvgr4 AS material_group4_mvgr4,
  lips.mvgr5 AS material_group5_mvgr5,
  lips.vpzuo AS allocation_indicator_vpzuo,
  lips.vgtyp AS sd_document_category_vgtyp,
  lips.rfvgtyp AS type_of_preceding_document_in_central_system_rfvgtyp,
  lips.kostl AS cost_center_kostl,
  lips.kokrs AS controlling_area_kokrs,
  lips.paobjnr AS profitability_segment_number_paobjnr,
  lips.prctr AS profit_center_prctr,
  lips.ps_psp_pnr AS work_breakdown_structure_element_wbs_element_ps_psp_pnr,
  lips.aufnr AS order_number_aufnr,
  lips.posnr_pp AS order_item_number_posnr_pp,
  lips.kdauf AS sales_order_number_kdauf,
  lips.kdpos AS item_number_in_sales_order_kdpos,
  lips.vpmat AS planning_material_vpmat,
  lips.vpwrk AS planning_plant_vpwrk,
  lips.prbme AS base_unit_of_measure_for_product_group_prbme,
  lips.umref AS conversion_factor_quantities_umref,
  lips.knttp AS account_assignment_category_knttp,
  lips.kzvbr AS consumption_posting_kzvbr,
  lips.fipos AS commitment_item_fipos,
  lips.fistl AS funds_center_fistl,
  lips.geber AS fund_geber,
  lips.pckpf AS packing_control_pckpf,
  lips.bedar_lf AS requirements_class_bedar_lf,
  lips.cmpnt AS id_item_with_active_credit_function_relevant_for_credit_cmpnt,
  lips.kcmeng AS cumulative_batch_quantity_of_all_split_items_in_stckunit_kcmeng,
  lips.kcbrgew AS cumulative_gross_weight_of_all_batch_split_items_kcbrgew,
  lips.kcntgew AS cumulative_net_weight_of_all_batch_split_items_kcntgew,
  lips.kcvolum AS cumulative_volume_of_all_batch_split_items_kcvolum,
  lips.uecha AS higher_level_item_of_batch_split_item_uecha,
  lips.cuobj AS configuration_cuobj,
  lips.cuobj_ch AS internal_object_number_of_the_batch_classification_cuobj_ch,
  lips.anzsn AS number_of_serial_numbers_anzsn,
  lips.serail AS serial_number_profile_serail,
  lips.kcgewei AS weight_unit_kcgewei,
  lips.kcvoleh AS volume_unit_kcvoleh,
  lips.sernr AS bom_explosion_number_sernr,
  lips.abrli AS internal_delivery_schedule_number_abrli,
  lips.abart AS rel_type_abart,
  lips.abrvw AS usage_indicator_abrvw,
  lips.qplos AS inspection_lot_number_qplos,
  lips.qtlos AS partial_lot_number_qtlos,
  lips.nachl AS customer_has_not_posted_goods_receipt_nachl,
  lips.magrv AS material_group_packaging_materials_magrv,
  lips.objko AS object_number_at_header_level_objko,
  lips.objpo AS object_number_at_item_level_objpo,
  lips.aeskd AS customer_engineering_change_status_aeskd,
  lips.shkzg AS returns_item_shkzg,
  lips.prosa AS id_for_material_determination_prosa,
  lips.uepvw AS higher_level_item_usage_uepvw,
  lips.empst AS receiving_point_empst,
  lips.abtnr AS department_number_abtnr,
  lips.koqui AS picking_is_subject_to_confirmation_koqui,
  lips.stadat AS statistics_date_stadat,
  lips.aktnr AS promotion_aktnr,
  lips.knumh_ch AS number_of_condition_record_from_batch_determination_knumh_ch,
  lips.prefe AS preference_indicator_in_exportimport_prefe,
  lips.exart AS business_transaction_type_for_foreign_trade_exart,
  lips.clint AS internal_class_number_clint,
  lips.chmvs AS batches_exit_to_quantity_proposal_chmvs,
  lips.abeln AS allocation_table_number_abeln,
  lips.abelp AS item_number_of_allocation_table_abelp,
  lips.lfimg_flo AS internal_field_do_not_use_lfimg_in_float_mum_lfimg_flo,
  lips.lgmng_flo AS internal_field_do_not_use_lgmng_in_float_mum_lgmng_flo,
  lips.kcmeng_flo AS internal_field_do_not_use_kcmeng_in_float_mum_kcmeng_flo,
  lips.kzumw AS environmentally_relevant_kzumw,
  lips.kmpmg AS component_quantity_kmpmg,
  lips.aurel AS relevant_to_allocation_table_aurel,
  lips.kpein AS condition_pricing_unit_kpein,
  lips.kmein AS condition_unit_kmein,
  ${currency.amountWithDecimalShift("lips.netpr", "currency_decimal")} AS net_price_netpr,
  ${currency.amountWithDecimalShift("lips.netwr", "currency_decimal")} AS net_value_in_document_currency_netwr,
  lips.kzbew AS movement_indicator_kzbew,
  lips.mfrgr AS material_freight_group_mfrgr,
  lips.chhpv AS pack_accumulated_batches_movement_type_item_chhpv,
  lips.abfor AS form_of_payment_guarantee_abfor,
  lips.abges AS guaranteed_factor_between0_and1_abges,
  lips.mbuhr AS material_staging_time_mbuhr,
  lips.wktnr AS value_contract_no_wktnr,
  lips.wktps AS value_contract_item_wktps,
  lips.j_1bcfop AS cfop_code_and_extension_j_1_bcfop,
  lips.j_1btaxlw1 AS tax_law_icms_j_1_btaxlw1,
  lips.j_1btaxlw2 AS tax_law_ipi_j_1_btaxlw2,
  lips.j_1btxsdc AS sd_tax_code_j_1_btxsdc,
  lips.situa AS indicator_for_situation_situa,
  lips.rsnum AS number_of_reservationdependent_requirements_rsnum,
  lips.rspos AS item_number_of_reservation_dependent_requirements_rspos,
  lips.rsart AS record_type_rsart,
  lips.kannr AS kanbansequence_number_kannr,
  lips.kzfme AS id_leading_unit_of_measure_for_completing_a_transaction_kzfme,
  lips.profl AS dangerous_goods_indicator_profile_profl,
  lips.kcmengvme AS cumulative_batch_quantity_of_all_split_items_in_sales_units_kcmengvme,
  lips.kcmengvmef AS cumulated_batch_split_quantity_in_vrkme_and_float_kcmengvmef,
  lips.kzbws AS valuation_of_special_stock_kzbws,
  lips.pspnr AS project_definition_internal_pspnr,
  lips.eprio AS withdrawal_sequence_group_for_stocks_eprio,
  lips.rules AS stock_determination_rule_rules,
  lips.kzbef AS indicator_inventory_management_active_kzbef,
  lips.mprof AS mfr_part_profile_mprof,
  lips.ematn AS material_number_corresponding_to_manufacturer_part_number_ematn,
  lips.lgbzo AS staging_area_for_warehouse_complex_lgbzo,
  lips.handle AS worldwide_unique_key_forlips_handle,
  lips.verurpos AS distribution_delivery_original_item_verurpos,
  lips.lifexpos AS external_item_number_lifexpos,
  lips.noatp AS indicator_deactivate_availability_check_noatp,
  lips.nopck AS indicator_not_relevant_for_picking_nopck,
  lips.rblvs AS reference_movement_type_for_wm_from_material_movements_rblvs,
  lips.berid AS mrp_area_berid,
  lips.bestq AS stock_category_in_the_warehouse_management_system_bestq,
  lips.umbsq AS stock_category_in_the_warehouse_management_system_umbsq,
  lips.ummat AS receiving_issuing_material_ummat,
  lips.umwrk AS receiving_plant_issuing_plant_umwrk,
  lips.umlgo AS receiving_issuing_storage_location_umlgo,
  lips.umcha AS receiving_issuing_batch_umcha,
  lips.umbar AS valuation_type_of_transfer_batch_umbar,
  lips.umsok AS special_stock_indicator_for_physical_stock_transfer_umsok,
  lips.sonum AS special_stock_number_sonum,
  lips.usonu AS special_stock_number_usonu,
  lips.akkur AS exchange_rate_for_letter_foreign_trade_akkur,
  lips.akmng AS current_qty_field_for_arithmetic_operations_akmng,
  lips.vkgru AS repair_processing_classification_of_items_vkgru,
  lips.shkzg_um AS indicator_unmat_in_main_posting_shkzg_um,
  lips.insmk AS stock_type_insmk,
  lips.kzech AS determination_of_batch_entry_in_the_productionprocess_order_kzech,
  lips.flgwm AS dest_storage_data_from_preceding_document_flgwm,
  lips.berkz AS material_staging_indicator_for_production_supply_berkz,
  lips.hupos AS indicator_delivery_item_is_a_hu_item_hupos,
  lips.nowab AS indicator_item_not_relevant_for_goods_movements_nowab,
  lips.konto AS gl_account_number_konto,
  lips.kzear AS final_issue_for_this_reservation_kzear,
  lips.hsdat AS date_of_manufacture_hsdat,
  lips.vfdat AS best_before_date_vfdat,
  lips.lfgja AS fiscal_year_of_current_period_lfgja,
  lips.lfbnr AS a_reference_document_lfbnr,
  lips.lfpos AS item_of_a_reference_document_lfpos,
  lips.grund AS reason_for_goods_movment_grund,
  lips.fobwa AS subsequent_movement_type_fobwa,
  lips.dlvtp AS delivery_category_dlvtp,
  ${currency.amountWithDecimalShift("lips.exbwr", "currency_decimal")} AS externally_entered_posting_amount_in_local_currency_exbwr,
  lips.bpmng AS quantity_in_purchase_order_price_unit_bpmng,
  ${currency.amountWithDecimalShift("lips.exvkw", "currency_decimal")} AS externally_entered_sales_value_in_local_currency_exvkw,
  lips.cmpre_flt AS item_credit_price_cmpre_flt,
  lips.kzpod AS pod_indicator_kzpod,
  lips.lfdez AS not_relevant_for_distribution_for_wms_lfdez,
  lips.umrev AS conversion_factor_of_delivery_quantity_vrkme_for_meins_umrev,
  lips.podrel AS pod_control_proof_of_delivery_podrel,
  lips.kzuml AS stock_transfertransfer_posting_kzuml,
  lips.fkber AS functional_area_fkber,
  lips.grant_nbr AS grant_grant_nbr,
  lips.kzwso AS units_of_measure_usage_kzwso,
  lips.gmcontrol AS goods_movement_control_gmcontrol,
  lips.posting_change AS goods_movement_control_hu_posting_change,
  lips.um_ps_psp_pnr AS receivingissuing_wbs_element_um_ps_psp_pnr,
  lips.pre_vl_etens AS sequential_number_of_vendor_confirmation_pre_vl_etens,
  lips.spe_gen_elikz AS delivery_completed_spe_gen_elikz,
  lips.spe_scrap_ind AS scrap_indicator_for_ewm_processing_spe_scrap_ind,
  lips.spe_auth_number AS return_material_authorization_number_spe_auth_number,
  lips.spe_inspout_guid AS inspections_inspection_outcome_guid_set_by_ewm_spe_inspout_guid,
  lips.spe_follow_up AS default_follow_spe_follow_up,
  lips.spe_exp_date_ext AS end_date_of_validity_period_of_returns_delivery_spe_exp_date_ext,
  lips.spe_exp_date_int AS end_date_of_internal_validity_period_of_returns_delivery_spe_exp_date_int,
  lips.spe_auth_complet AS rma_completion_indicator_spe_auth_complet,
  lips.ormng AS original_quantity_of_delivery_item_ormng,
  lips.spe_atp_tmstmp AS atp_time_stamp_spe_atp_tmstmp,
  lips.spe_orig_sys AS original_system_type_itm_spe_orig_sys,
  lips.spe_lieffz AS cumulative_qty_for_schedagr_vendor_pov_spe_lieffz,
  lips.spe_imwrk AS inbound_delivery_item_has_statusin_plant_spe_imwrk,
  lips.spe_lifexpos2 AS external_item_identifier_spe_lifexpos2,
  lips.spe_except_code AS exception_code_warehouse_for_quantity_difference_spe_except_code,
  lips.spe_keep_qty AS retention_quantity_for_scrap_spe_keep_qty,
  lips.spe_alternate AS alternate_product_number_spe_alternate,
  lips.spe_mat_subst AS reason_for_material_substitution_spe_mat_subst,
  lips.spe_struc AS structure_of_items_that_are_delivered_together_spe_struc,
  lips.spe_apo_qntyfac AS numerator_of_quotient_for_unit_of_measure_conversion_spe_apo_qntyfac,
  lips.spe_apo_qntydiv AS denominator_of_quotient_for_unit_of_measure_conversion_spe_apo_qntydiv,
  lips.spe_herkl AS non_preferential_origin_spe_herkl,
  lips.spe_bxp_date_ext AS begin_date_of_validity_period_of_returns_delivery_spe_bxp_date_ext,
  lips.spe_version AS delivery_version_at_confirmation_spe_version,
  lips.spe_compl_mvt AS completion_of_goods_movements_after_difference_postings_spe_compl_mvt,
  lips.j_1btaxlw4 AS cofins_tax_law_j_1_btaxlw4,
  lips.j_1btaxlw5 AS pis_tax_law_j_1_btaxlw5,
  lips.j_1btaxlw3 AS iss_tax_law_j_1_btaxlw3,
  lips.budget_pd AS fm_budget_period_budget_pd,
  lips.kbnkz AS kanban_indicator_kbnkz,
  lips.sitkz AS specification_for_issuing_valuated_stock_in_transit_sitkz,
  lips.cons_order AS purchase_order_for_consignment_cons_order,
  lips.aufpl AS routing_number_for_operations_aufpl,
  lips.aplzl AS counter_aplzl,
  lips.farr_reltype AS revenue_accounting_type_farr_reltype,
  lips.sgt_rcat AS requirement_segment_sgt_rcat,
  lips.sgt_scat AS stock_segment_sgt_scat,
  lips.resource_id AS delivery_item_resource_id_resource_id,
  lips.loading_point AS loading_unloading_point_loading_point,
  lips.solution_order_id AS solution_order_id,
  lips.solution_order_itm_id AS item_number_in_document_solution_order_itm_id,
  lips.spe_herkr AS region_of_origin_spe_herkr,
  lips.itm_comco AS commodity_code_itm_comco,
  lips.besta AS item_status_besta,
  lips.cmppi AS credit_management_item_status_cmppi,
  lips.cmppj AS credit_management_payment_card_status_cmppj,
  lips.fkivp AS intercompany_billing_status_fkivp,
  lips.fksta AS delivery_related_billing_status_fksta,
  lips.gbsta AS sd_process_status_gbsta,
  lips.hdall AS delivery_item_not_complete_hdall,
  lips.koqua AS picking_confirmation_status_koqua,
  lips.kosta AS picking_status_kosta,
  lips.lvsta AS warehouse_activity_status_lvsta,
  lips.pdsta AS proof_of_delivery_status_pdsta,
  lips.pksta AS packing_status_pksta,
  lips.uvall AS item_general_incompletion_status_uvall,
  lips.uvfak AS item_billing_incompletion_status_uvfak,
  lips.uvpak AS item_packing_incompletion_status_uvpak,
  lips.uvpik AS item_picking_incompletion_status_uvpik,
  lips.uvvlk AS item_delivery_incompletion_status_uvvlk,
  lips.uvwak AS item_goods_movement_incompletion_status_uvwak,
  lips.vlstp AS distribution_status_vlstp,
  lips.wbsta AS goods_movement_status_wbsta,
  lips.uvp01 AS incompletion_status_1_uvp01,
  lips.uvp02 AS incompletion_status_2_uvp02,
  lips.uvp03 AS incompletion_status_3_uvp03,
  lips.uvp04 AS incompletion_status_4_uvp04,
  lips.uvp05 AS incompletion_status_5_uvp05,
  lips.emcst AS trade_compliance_embargo_status_emcst,
  lips.slcst AS trade_compliance_sanctioned_list_check_status_slcst,
  lips.lccst AS trade_compliance_legal_control_status_lccst,
  lips.pcsta AS chemical_compliance_status_pcsta,
  lips.dgsta AS dangerous_goods_status_dgsta,
  lips.sdssta AS safety_data_sheet_status_sdssta,
  lips.sapmp_lbasp AS dtuc_status_sapmp_lbasp,
  lips.arc_status AS eu_delivery_item_arc_status_arc_status,
  lips.cwm_lfimg AS delivery_quantity_parallel_unit_of_measure_cwm_lfimg,
  lips.cwm_lfime AS cwm_delivery_unit_cwm_lfime,
  lips.cwm_pikmg AS picked_quantity_parallel_unit_of_measure_cwm_pikmg,
  lips.cwm_pikme AS parallel_unit_of_measure_picked_quantity_cwm_pikme,
  lips.cwm_xenter AS parallel_quantity_entered_cwm_xenter,
  lips.cwm_xtaenter AS transfer_order_cwm_xtaenter,
  lips.cwm_kcmeng AS accumulated_cw_batch_quantity_cwm_kcmeng,
  lips.cwm_ebumg AS quantity_to_be_posted_parallel_unit_of_measure_cwm_ebumg,
  lips.dummy_delitm_incl_eew_ps AS dummy_delivery_item_dummy_delitm_incl_eew_ps,
  lips.kjedm_inverted AS inverted_kjedm_inverted,
  lips.sapmp_lba_no AS dtuc_sapmp_lba_no,
  lips.sapmp_alt_conv AS provisional_conversion_factors_sapmp_alt_conv,
  lips.lgtor AS door_lgtor,
  dimensional_date_erdat.cal_year AS year_of_creation_date_erdat,
  dimensional_date_erdat.cal_month AS month_of_creation_date_erdat,
  dimensional_date_erdat.cal_week AS week_of_creation_date_erdat,
  dimensional_date_erdat.day_of_month AS day_of_month_of_creation_date_erdat,
  dimensional_date_erdat.cal_quarter AS quarter_of_creation_date_erdat,
  IFNULL(
    lips.recordstamp,
    TIMESTAMP('1900-01-01 00:00:00+00')
  ) AS source_last_updated_at,
  CURRENT_TIMESTAMP() AS bq_loaded_at
FROM
  ${ctx.ref(moduleConfig.sources.sapModule.datasetId, "lips")} AS lips
LEFT JOIN
  ${ctx.ref(moduleConfig.sources.sapModule.datasetId, 'likp')} as likp
  ON lips.mandt = likp.mandt
  AND lips.vbeln = likp.vbeln
LEFT JOIN date_dimension AS dimensional_date_erdat
  ON lips.erdat = dimensional_date_erdat.date
LEFT JOIN currency_decimal
  ON likp.waerk = currency_decimal.currkey
${incremental.getWhere(ctx, "lips.recordstamp")}
  `,
  );