/**
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

const moduleContext = {
  "moduleId": "sap_delivery_documents"
};
const tableConfig = {
  "tags": [
    "sap",
    "dataproduct",
    "transactional"
  ],
  "materializationType": "incremental",
  "description": "Information about delivery documents at the header level at the granularity of Client(System) and Delivery document number.",
  "columns": {
    "client_mandt": "Client (Mandant), PK",
    "document_number_vbeln": "Delivery Document Number, PK",
    "created_by_ernam": "Name of the person who created the delivery document",
    "creation_time_erzet": "Time of creation (Entry time) of the delivery document",
    "creation_date_erdat": "Date of creation of the delivery document",
    "sales_district_bzirk": "Sales District",
    "shipping_point_receiving_point_vstel": "Shipping Point/Receiving Point",
    "sales_organization_vkorg": "Sales Organization",
    "delivery_type_lfart": "Delivery Type",
    "complete_delivery_defined_indicator_autlf": "Indicates whether all items in a sales order should be delivered together in a single delivery, rather than in partial deliveries.",
    "order_combination_indicator_kzazu": "Indicates whether multiple sales orders can be combined into a single delivery document.",
    "planned_goods_movement_date_wadat": "Planned goods movement date",
    "loading_date_lddat": "Loading date",
    "transportation_planning_date_tddat": "Transporation planning date",
    "delivery_date_lfdat": "Delivery date",
    "picking_date_kodat": "Picking date",
    "unloading_point_ablad": "Unloading point",
    "incoterms_part1_inco1": "Incoterms (Part 1)",
    "incoterms_part2_inco2": "Incoterms (Part 2)",
    "export_indicator_expkz": "Export indicator",
    "route_route": "Route. It represents the planned transportation route for the delivery.",
    "billing_block_in_sales_document_faksk": "Billing block in sales document",
    "delivery_block_document_header_lifsk": "Delivery block in delivery document header",
    "sales_document_category_vbtyp": "Sales document category",
    "customer_factory_calendar_knfak": "Customer factory calendar",
    "delivery_priority_lprio": "Delivery priority",
    "shipping_conditions_vsbed": "Shipping conditions",
    "ship_to_party_kunnr": "Ship-to party",
    "sold_to_party_kunag": "Sold-to party",
    "customer_group_kdgrp": "Customer group",
    "total_weight_btgew": "Total weight",
    "net_weight_ntgew": "Net weight",
    "weight_unit_gewei": "Weight unit",
    "volume_volum": "Volume",
    "volume_unit_voleh": "Volume unit",
    "total_packages_anzpk": "Total packages",
    "picked_items_location_berot": "Picked items location",
    "delivery_time_lfuhr": "Delivery time",
    "weight_group_grulg": "Weight group for delivery (To group)",
    "loading_point_lstel": "Loading point",
    "transportation_group_tragr": "Transportation group",
    "proposed_billing_type_fkarv": "Proposed billing type for a delivery related billing document.",
    "proposed_billing_date_fkdat": "Proposed billing date for billing index and printout",
    "invoice_dates_perfk": "Invoice dates (calendar identification). It represents the Invoice Date Profile or Invoice Date Formula for the delivery.",
    "route_routa": "Route.  It represents the the specific route or itinerary assigned to a delivery document.",
    "update_group_for_statistics_stafo": "Update group for statistics. It determines the update group is utilized for updating statistics in logistics information systems.",
    "procedure_kalsm": "Pricing Procedure (or Calculation Procedure) that is applied to the delivery document.",
    "condition_number_knumv": "Number of the document condition. It is a unique identifier for the condition record used in pricing.",
    "sales_document_currency_waerk": "Currency of the sales document.",
    "sales_office_vkbur": "Sales Office.",
    "shipping_processing_time_vbeak": "Shipping processing time for the entire document.",
    "delivery_combination_criteria_zukrl": "Combination criteria for delivery.",
    "distribution_delivery_verur": "Distribution delivery.",
    "communication_number_commn": "Communication number for Q-API interface.",
    "statistics_currency_stwae": "Statistics currency.",
    "statistics_exchange_rate_stcur": "Exchange rate for statistics.",
    "foreign_trade_data_number_exnum": "Number of foreign trade data in Materials Management (MM) and Sales and Distribution (SD) documents",
    "changed_by_aenam": "Changed by",
    "changed_on_aedat": "Changed on",
    "warehouse_number_lgnum": "Warehouse Number / Warehouse Complex.",
    "delivery_within_one_warehouse_lispl": "Delivery within one warehouse.",
    "intercompany_billing_sales_organization_vkoiv": "Sales organization for intercompany billing.",
    "intercompany_billing_distribution_channel_vtwiv": "Distribution channel for intercompany billing.",
    "intercompany_billing_division_spaiv": "Division for intercompany billing.",
    "intercompany_billing_type_fkaiv": "Billing type for intercompany billing.",
    "intercompany_billing_price_date_pioiv": "Price date for intercompany billing. It determines the date on which the price is calculated for the invoice between company codes.",
    "intercompany_billing_date_fkdiv": "Billing date for intercompany billing.",
    "intercompany_billing_customer_number_kuniv": "Customer number for intercompany billing.",
    "credit_control_area_kkber": "Credit control area.",
    "credit_account_knkli": "Credit account used to determine the credit limit for the customer in that delivery, usually based on the payer assigned to the shipment.",
    "customer_credit_group_grupp": "Customer credit group.",
    "credit_representative_group_sbgrp": "Credit representative group for credit management.",
    "credit_management_risk_category_ctlpc": "Credit management risk category.",
    "credit_control_area_currency_key_cmwae": "Currency key of the credit control area.",
    "released_credit_value_amtbl": "Released credit value of the document.",
    "bill_of_lading_bolnr": "Bill of lading number.",
    "vendor_account_number_lifnr": "Vendor account number.",
    "means_of_transport_type_traty": "Means of transport type.",
    "means_of_transport_id_traid": "Means of transport identification.",
    "credit_release_date_cmfre": "Release date of the document determined by credit management. the specific date on which a delivery document, which was previously blocked due to credit checks, was formally released by authorized personnel.",
    "next_date_cmngv": "Next delivery relevant date. e.g.,the next planned picking date or goods issue date (typically populated after picking has occurred).",
    "goods_receipt_issue_slip_number_xabln": "Goods receipt/issue slip number.",
    "document_date_bldat": "Document date in the delivery document. It is the date on which the delivery document was created or the date stated on the original, physical document, may differ from the system creation_date_erdat or the planned_goods_movement_date_wadat.",
    "actual_goods_movement_date_wadat_ist": "Actual goods movement date.",
    "shipment_blocking_reason_trspg": "Shipment blocking reason.",
    "external_transport_system_id_tpsid": "ID for external transport system.",
    "external_delivery_note_id_lifex": "External Identification of Delivery Note.",
    "order_number_ternr": "Order Number associated with a specific delivery. A link back to a specific upstream document.",
    "batch_search_procedure_kalsm_ch": "Search procedure for batch determination.",
    "correction_delivery_klief": "Correction delivery.",
    "shipping_pricing_procedure_kalsp": "Shipping pricing procedure.",
    "pricing_condition_number_knump": "Number of document condition - pricing. Used when pricing needs to be updated or recalculating during delivery creation rather than relying solely on the sales order pricing.",
    "net_value_in_document_currency_netwr": "Net value of the related order in document currency.",
    "route_schedule_aulwe": "Route schedule",
    "receiving_plant_werks": "Receiving plant for deliveries.",
    "internal_financial_document_number_lcnum": "Financial document processing: Internal financial doc. number",
    "payment_guarantee_procedure_abssc": "Payment guarantee procedure.",
    "picking_time_kouhr": "Picking time (local time, with reference to a plant)",
    "transportation_planning_time_tduhr": "Transportation Planning Time (Local, Relating to a Shipping Point)",
    "loading_time_lduhr": "Loading Time (Local, Relating to a Shipping Point)",
    "goods_issue_time_wauhr": "Time of Goods Issue (Local, Relating to a Shipping Point)",
    "warehouse_door_number_lgtor": "Door for Warehouse Number.",
    "warehouse_staging_area_lgbzo": "Staging area for warehouse complex.",
    "foreign_trade_currency_key_akwae": "Currency key for letter-of-credit processing in foreign trade",
    "foreign_trade_exchange_rate_akkur": "Exchange rate for letter-of-credit processing in foreign trade",
    "depreciation_percentage_akprz": "Depreciation percentage for financial document processing.",
    "dangerous_goods_management_profile_proli": "Dangerous goods management profile for sales documents.",
    "reference_document_number_xblnr": "Reference document number.",
    "worldwide_unique_key_handle": "Worldwide unique key for delivery document header.",
    "time_segment_exists_indicator_tsegfl": "Time segment exists indicator.",
    "event_group_time_segment_delivery_header_tsegtp": "Event group time segment delivery header.",
    "delivery_location_timezone_tzonis": "Time zone of delivering location.",
    "recipient_location_timezone_tzonrc": "Time zone of recipient location.",
    "dangerous_goods_indicator_cont_dg": "Indicator whether the delivery contains dangerous goods.",
    "distribution_delivery_original_system_verursys": "Distribution delivery: original system.",
    "goods_movement_control_indicator_kzwab": "Indicator for controlling goods movement.",
    "distribution_status_vlstk": "Distribution Status (Decentralized Warehouse Processing)",
    "transaction_code_tcode": "Transaction code.",
    "shipping_type_vsart": "Shipping type.",
    "means_of_transport_trmtyp": "Means of transport type.",
    "special_processing_indicator_sdabw": "Special processing indicator.",
    "company_id_vbund": "Company ID.",
    "calculation_of_value_open_indicator_xwoff": "Indicates wheteher the tax calculation or specific value-based calculations are switched off or excluded.",
    "automatic_transportation_order_creation_indicator_dirta": "Indicates whether the automatic creation of transportation orders is triggered immediately after the creation of a transfer requirement.",
    "production_supply_area_prvbe": "Production supply area.",
    "delivery_type_folar": "Delivery type.",
    "proof_of_delivery_date_podat": "Date of proof of delivery.",
    "proof_of_delivery_confirmation_time_potim": "Confirmation time of proof of delivery.",
    "shipment_document_total_count_vganz": "The total count of shipment documents assigned to the specific delivery header.",
    "goods_movement_within_company_code_indicator_imwrk": "Indicates whether the goods movement (goods issue) for the delivery should be posted within the same company code or if it involves cross-company code transactions",
    "document_deletion_indicator_spe_loekz": "Indicates whether the delivery document has been deleted.",
    "locations_sequenece_number_spe_loc_seq": "locations_sequenece_number_spe_loc_seq mapped from SPE_LOC_SEQ",
    "delivery_confirmation_status_spe_acc_app_sts": "Delivery confirmation status.",
    "shipment_information_status_spe_shp_inf_sts": "Shipment information status.",
    "return_document_cancellation_indicator_spe_ret_canc": "Return document cancellation indicator.",
    "goods_issue_time_spe_wauhr_ist": "Time of Goods Issue (Local, Relating to a Plant)",
    "goods_issue_time_zone_spe_wazone_ist": "Time Zone",
    "revenue_recognition_status_spe_rev_vlstk": "Revenue Recognition Status",
    "logistics_execution_scenario_spe_le_scenario": "Logistics Execution Scenario",
    "original_system_type_spe_orig_sys": "Original System Type",
    "last_changer_system_type_spe_chng_sys": "Last Changer System Type",
    "geographical_route_description_spe_georoute": "Description of a Geographical Route",
    "route_change_indicator_spe_georouteind": "Indicator for the route change",
    "carrier_change_indicator_spe_carrier_ind": "Indicator for the carrier change",
    "goods_traffic_type_spe_gts_rel": "Goods Traffic Type",
    "sap_global_trade_services_route_code_spe_gts_rt_cde": "SAP Global Trade Services Route Code",
    "release_time_stamp_spe_rel_tmstmp": "Release Time Stamp",
    "measurement_unit_system_spe_unit_system": "Measurement Unit System",
    "invoice_creation_before_goods_issue_spe_inv_bfr_gi": "Invoice Creation Before Goods Issue",
    "return_delivery_quality_inspection_status_spe_qi_status": "Status of Quality Inspection for Returns Deliveries",
    "redirection_indicator_spe_red_ind": "Indicates whether a redirection has occured.",
    "sap_global_trade_services_delivery_storage_status_sakes": "SAP Global Trade Services storage status of delivery.",
    "external_identification_type_spe_lifex_type": "Type of external identification.",
    "means_of_transport_spe_ttype": "Means of transport.",
    "progressive_identification_number_spe_pro_number": "Partner Identification : Progressive Identification Number.",
    "location_guid_loc_guid": "Location GUID.",
    "ewm_billing_indicator_spe_billing_ind": "EWM Billing Indicator.",
    "print_profile_description_printer_profile": "Print Profile Description",
    "advanced_returns_management_active_msr_active": "Advanced Returns Management Active",
    "confirmation_number_prtnr": "Confirmation Number",
    "storage_location_change_stge_loc_change": "Temporary Change of Storage Locations in Delivery.",
    "document_transfer_control_key_tm_ctrl_key": "Document Transfer to Transportation Managemnt Control Key",
    "delivery_split_initiator_dlv_split_initia": "Delivery Split Initiator",
    "delivery_version_dlv_version ": "Delivery Version",
    "previous_document_type_gts_vorpa": "Previous Document Type",
    "previous_document_number_gts_vornu": "Previous Document Number",
    "intrastat_border_mode_of_transport_gts_expvz": "Intrastat Border Mode of Transport",
    "port_airport_gts_porti": "Port Airport",
    "border_means_of_transport_itm_expvz": "Border Means of Transport",
    "origin_border_means_of_transport_itm_stgbe": "Origin Border Means of Transport",
    "border_cross_means_of_transport_id_itm_kzgbe": "Border Cross Means of Transport ID",
    "cross_border_conveyance_reference_id_itm_vygid": "Cross Border Conveyance Reference ID",
    "inland_means_of_transport_itm_iever": "Inland Means of Transport",
    "country_of_origin_means_of_transport_itm_stabe": "Country of Origin Means of Transport",
    "inland_means_of_transport_id_itm_kzabe": "Inland Means of Transport ID",
    "handover_location_handoverloc": "Location for a physical handover of goods",
    "handover_date_handoverdate": "Handover Date at the Handover Location",
    "handover_time_handovertime": "Handover Time at the Handover Location",
    "handover_time_zone_handovertzone": "Handover Time Zone",
    "delivery_confirmation_status_bestk": "Delivery Confirmation Status",
    "maximum_document_value_credit_check_status_cmpsc": "Maximum Document Value Credit Check Status",
    "terms_of_payment_credit_check_status_cmpsd": "Terms of Payment Credit Check Status",
    "financial_document_credit_check_status_cmpsi": "Financial Document Credit Check Status",
    "export_credit_insurance_credit_check_status_cmpsj": "Export Credit Insurance Credit Check Status",
    "payment_card_authorization_credit_check_status_cmpsk": "Payment Card Authorization Credit Check Status",
    "sap_credit_management_credit_check_status_cmps_cm": "SAP Credit Management Credit Check Status",
    "sap_credit_management_technical_error_status_cmps_te": "SAP Credit Management Technical Error Status",
    "credit_checks_overall_status_cmgst": "Credit Checks Overall Status",
    "intercompany_billing_status_fkivk": "Intercompany Billing Status",
    "delivery_related_billing_status_fkstk": "Delivery Related Billing Status",
    "overall_processing_status_gbstk": "Overall Processing Status",
    "incomplete_inbound_delivery_header_indicator_hdall": "Incomplete Inbound Delivery Header Indicator",
    "incomplete_inbound_delivery_item_indicator_hdals": "Incomplete Inbound Delivery Item Indicator",
    "pick_confirmation_status_koquk": "Pick Confirmation Status",
    "picking_status_kostk": "Picking Status",
    "warehouse_management_status_lvstk": "Warehouse Management Status",
    "pod_header_status_pdstk": "POD Header Status",
    "packing_status_pkstk": "Packing Status",
    "temporary_inbound_delivery_indicator_spe_tmpid": "Temporary Inbound Delivery Indicator",
    "overall_header_block_status_spstg": "Overall Header Block Status",
    "transportation_planning_status_trsta": "Transportation Planning Status",
    "header_incompletion_status_uvall": "Header Incompletion Status",
    "items_incompletion_status_uvals": "Items Incompletion Status",
    "header_billing_incompletion_status_uvfak": "Header Billing Incompletion Status",
    "items_billing_incompletion_status_uvfas": "Items Billing Incompletion Status",
    "header_packing_incompletion_status_uvpak": "Header Packing Incompletion Status",
    "items_packing_incompletion_status_uvpas": "Items Packing Incompletion Status",
    "header_picking_incompletion_status_uvpik": "Header Picking Incompletion Status",
    "items_picking_incompletion_status_uvpis": "Items Picking Incompletion Status",
    "header_delivery_incompletion_status_uvvlk": "Header Delivery Incompletion Status",
    "items_delivery_incompletion_status_uvvls": "Items Delivery Incompletion Status",
    "header_goods_movement_incompletion_status_uvwak": "Header Goods Movement Incompletion Status",
    "items_goods_movement_incompletion_status_uvwas": "Items Goods Movement Incompletion Status",
    "handling_unit_in_stock_indicator_vestk": "Handling Unit In Stock Indicator",
    "goods_movement_status_wbstk": "Goods Movement Status",
    "header_customer_reserve_status1_suvk01": "Header Customer Reserve Status 1",
    "header_customer_reserve_status2_suvk02": "Header Customer Reserve Status 2",
    "header_customer_reserve_status3_suvk03": "Header Customer Reserve Status 3",
    "header_customer_reserve_status4_suvk04": "Header Customer Reserve Status 4",
    "header_customer_reserve_status5_suvk05": "Header Customer Reserve Status 5",
    "item_customer_reserve_status1_suvs01": "Item Customer Reserve Status 1",
    "item_customer_reserve_status2_suvs02": "Item Customer Reserve Status 2",
    "item_customer_reserve_status3_suvs03": "Item Customer Reserve Status 3",
    "item_customer_reserve_status4_suvs04": "Item Customer Reserve Status 4",
    "item_customer_reserve_status5_suvs05": "Item Customer Reserve Status 5",
    "total_product_marketability_check_status_total_pcsta": "Total Product Marketability Check Status",
    "total_dangerous_goods_check_status_total_dgsta": "Total Dangerous Goods Check Status",
    "total_safety_data_sheet_check_status_total_sdssta": "Total Safety Data Sheet Check Status",
    "excise_tax_total_header_status_total_arc_status": "Excise Tax Total Header Status",
    "dtuc_status_sapmp_lbask": "DTUC Status",
    "incoterms_version_incov": "Incoterms Version",
    "incoterms_location_1_inco2_l": "Incoterms Location 1",
    "incoterms_location_2_inco3_l": "Incoterms Location 2",
    "external_billing_of_lading_oid_extbol": "External Billing of Lading",
    "miscellaneous_delivery_number_oid_miscdl": "Miscellaneous Delivery Number",
    "external_business_system_id_ext_bus_syst_id": "External Business System ID",
    "valuated_stock_in_transit_issue_specification_sitkz_db": "Valuated Stock in Transit Issue Specification",
    "advanced_shipping_receipt_relevance_indicator_tm_adv_ship_recv": "Advanced Shipping Receipt Relevance Indicator",
    "warehouse_execution_status_tm_whse_exec": "Warehouse Execution Status",
    "loading_units_bev1_luleinh": "Loading Units",
    "number_category_1_bev1_rpfaess": "Number Category 1",
    "number_category_2_bev1_rpkist": "Number Category 2",
    "number_category_3_bev1_rpcont": "Number Category 3",
    "number_category_4_bev1_rpsonst": "Number Category 4",
    "tour_loading_sequqnce_number_bev1_rpflgnr": "Tour Loading Sequence Number",
    "tracking_last_notified_route_point_idt_cur_evtloc": "Tracking Last Notified Route Point",
    "tracking_arrival_departure_indicator_idt_cur_evtqua": "Tracking Arrival Departure Indicator",
    "tracking_current_point_event_timestamp_idt_cur_evttst": "Tracking Current Point Event Timestamp",
    "tracking_current_point_time_estimation_base_point_idt_cur_estloc": "Tracking Current Point Time Estimation Base Point",
    "tracking_current_point_arrival_departure_time_estimation_idt_cur_estqua": "Tracking Current Point Arrival Departure Time Estimation",
    "tracking_current_point_delivery_date_estimation_base_date_idt_cur_esttst": "Tracking Current Point Delivery Date Estimation Base Date",
    "tracking_current_point_entry_qualifiers_idt_cur_wrkqua": "Tracking Current Point Entry Qualifiers",
    "tracking_prior_point_idt_pre_evtloc": "Tracking Prior Point",
    "tracking_prior_point_arrival_departure_indicator_idt_pre_evtqua": "Tracking Prior Point Arrival Departure Indicator",
    "tracking_prior_point_event_timestamp_idt_pre_evttst": "Tracking Prior Point Event Timestamp",
    "tracking_prior_point_time_estimation_base_point_idt_pre_estloc": "Tracking Prior Point Time Estimation Base Point",
    "tracking_prior_point_arrival_departure_time_estimation_idt_pre_estqua": "Tracking Prior Point Arrival Departure Time Estimation",
    "tracking_prior_point_delivery_date_estimation_base_date_idt_pre_esttst": "Tracking Prior Point Delivery Date Estimation Base Date",
    "tracking_prior_point_entry_qualifiers_idt_pre_wrkqua": "Tracking Prior Point Entry Qualifiers",
    "tracking_reference_point_time_estimation_base_point_idt_ref_estloc": "Tracking Reference Point Time Estimation Base Point",
    "tracking_reference_point_arrival_departure_time_estimation_idt_ref_estqua": "Tracking Reference Point Arrival Departure Time Estimation",
    "tracking_reference_point_delivery_date_estimation_base_date_idt_ref_esttst": "Tracking Reference Point Delivery Date Estimation Base Date",
    "delivery_date_time_commitment_level_idt_firm_lfdat": "Delivery Date Time Commitment Level",
    "document_number_idt_docnum": "Document Number",
    "multi_level_goods_receipt_automotive_borgr_grp": "Inbound Delivery Group: Multi-Level Goods Receipt Automotive",
    "kanban_indicator_kbnkz": "Kanban Indicator",
    "psst_group_rfm_psst_group": "PSST Group",
    "jit_relevant_indicator_jit_rlvnt": "JIT Relevant Indicator",
    "year_of_delivery_date_lfdat": "Year of delivery date",
    "month_of_delivery_date_lfdat": "Month of delivery date",
    "quarter_of_delivery_date_lfdat": "Quarter of delivery date",
    "week_of_delivery_date_lfdat": "Week of delivery date",
    "year_of_proof_of_delivery_date_podat": "Year of proof of delivery date",
    "month_of_proof_of_delivery_date_podat": "Month of proof of delivery date",
    "quarter_of_proof_of_delivery_date_podat": "Quarter of proof of delivery date",
    "week_of_proof_of_delivery_date_podat": "Week of proof of delivery date",
    "year_of_document_date_bldat": "Year of document date",
    "month_of_document_date_bldat": "Month of document date",
    "quarter_of_document_date_bldat": "Quarter of document date",
    "week_of_document_date_bldat": "Week of document date",
    "source_last_updated_at": "Source Last Updated At",
    "bq_loaded_at": "BigQuery Loaded At"
  }
};

const moduleConfig = config.product[moduleContext.moduleId];

const materializationType = tableConfig.materializationType || "incremental";

const currency = require("includes/cortex/currency.js");
const date = require("includes/cortex/date.js");
const incremental = require("includes/cortex/incremental.js");
const publish_config = require("includes/cortex/publish_config.js");

const publishConfig = publish_config.getPublishConfig(
  materializationType,
  tableConfig,
  moduleConfig,
  [
    "client_mandt",
    "document_number_vbeln"
  ]
);

publish("delivery_document_headers", publishConfig).query(
  (ctx) => `
WITH date_dimension AS (
  ${date.getDateDimension()}
),
currency_decimal AS (
  ${currency.currencyDecimalShift(ctx.ref(moduleConfig.sources.sapModule.datasetId, "tcurx"))}
)
SELECT
  likp.mandt AS client_mandt,
  likp.vbeln AS document_number_vbeln,
  likp.ernam AS created_by_ernam,
  likp.erzet AS creation_time_erzet,
  likp.erdat AS creation_date_erdat,
  likp.bzirk AS sales_district_bzirk,
  likp.vstel AS shipping_point_receiving_point_vstel,
  likp.vkorg AS sales_organization_vkorg,
  likp.lfart AS delivery_type_lfart,
  likp.autlf AS complete_delivery_defined_indicator_autlf,
  likp.kzazu AS order_combination_indicator_kzazu,
  likp.wadat AS planned_goods_movement_date_wadat,
  likp.lddat AS loading_date_lddat,
  likp.tddat AS transportation_planning_date_tddat,
  likp.lfdat AS delivery_date_lfdat,
  likp.kodat AS picking_date_kodat,
  likp.ablad AS unloading_point_ablad,
  likp.inco1 AS incoterms_part1_inco1,
  likp.inco2 AS incoterms_part2_inco2,
  likp.expkz AS export_indicator_expkz,
  likp.route AS route_route,
  likp.faksk AS billing_block_in_sales_document_faksk,
  likp.lifsk AS delivery_block_document_header_lifsk,
  likp.vbtyp AS sales_document_category_vbtyp,
  likp.knfak AS customer_factory_calendar_knfak,
  likp.lprio AS delivery_priority_lprio,
  likp.vsbed AS shipping_conditions_vsbed,
  likp.kunnr AS ship_to_party_kunnr,
  likp.kunag AS sold_to_party_kunag,
  likp.kdgrp AS customer_group_kdgrp,
  likp.btgew AS total_weight_btgew,
  likp.ntgew AS net_weight_ntgew,
  likp.gewei AS weight_unit_gewei,
  likp.volum AS volume_volum,
  likp.voleh AS volume_unit_voleh,
  likp.anzpk AS total_packages_anzpk,
  likp.berot AS picked_items_location_berot,
  likp.lfuhr AS delivery_time_lfuhr,
  likp.grulg AS weight_group_grulg,
  likp.lstel AS loading_point_lstel,
  likp.tragr AS transportation_group_tragr,
  likp.fkarv AS proposed_billing_type_fkarv,
  likp.fkdat AS proposed_billing_date_fkdat,
  likp.perfk AS invoice_dates_perfk,
  likp.routa AS route_routa,
  likp.stafo AS update_group_for_statistics_stafo,
  likp.kalsm AS procedure_kalsm,
  likp.knumv AS condition_number_knumv,
  likp.waerk AS sales_document_currency_key_waerk,
  likp.vkbur AS sales_office_vkbur,
  likp.vbeak AS shipping_processing_time_vbeak,
  likp.zukrl AS delivery_combination_criteria_zukrl,
  likp.verur AS distribution_delivery_verur,
  likp.commn AS communication_number_commn,
  likp.stwae AS statistics_currency_stwae,
  likp.stcur AS statistics_exchange_rate_stcur,
  likp.exnum AS foreign_trade_data_number_exnum,
  likp.aenam AS changed_by_aenam,
  likp.aedat AS changed_on_aedat,
  likp.lgnum AS warehouse_number_lgnum,
  likp.lispl AS delivery_within_one_warehouse_lispl,
  likp.vkoiv AS intercompany_billing_sales_organization_vkoiv,
  likp.vtwiv AS intercompany_billing_distribution_channel_vtwiv,
  likp.spaiv AS intercompany_billing_division_spaiv,
  likp.fkaiv AS intercompany_billing_type_fkaiv,
  likp.pioiv AS intercompany_billing_price_date_pioiv,
  likp.fkdiv AS intercompany_billing_date_fkdiv,
  likp.kuniv AS intercompany_billing_customer_number_kuniv,
  likp.kkber AS credit_control_area_kkber,
  likp.knkli AS credit_account_knkli,
  likp.grupp AS customer_credit_group_grupp,
  likp.sbgrp AS credit_representative_group_sbgrp,
  likp.ctlpc AS credit_management_risk_category_ctlpc,
  likp.cmwae AS credit_control_area_currency_key_cmwae,
  likp.amtbl AS released_credit_value_amtbl,
  likp.bolnr AS bill_of_lading_bolnr,
  likp.lifnr AS vendor_account_number_lifnr,
  likp.traty AS means_of_transport_type_traty,
  likp.traid AS means_of_transport_id_traid,
  likp.cmfre AS credit_release_date_cmfre,
  likp.cmngv AS next_date_cmngv,
  likp.xabln AS goods_receipt_issue_slip_number_xabln,
  likp.bldat AS document_date_bldat,
  likp.wadat_ist AS actual_goods_movement_date_wadat_ist,
  likp.trspg AS shipment_blocking_reason_trspg,
  likp.tpsid AS external_transport_system_id_tpsid,
  likp.lifex AS external_delivery_note_id_lifex,
  likp.ternr AS order_number_ternr,
  likp.kalsm_ch AS batch_search_procedure_kalsm_ch,
  likp.klief AS correction_delivery_klief,
  likp.kalsp AS shipping_pricing_procedure_kalsp,
  likp.knump AS pricing_condition_number_knump,
  ${currency.amountWithDecimalShift("likp.netwr", "currency_decimal")} AS net_value_in_document_currency_netwr,
  likp.aulwe AS route_schedule_aulwe,
  likp.werks AS receiving_plant_werks,
  likp.lcnum AS internal_financial_document_number_lcnum,
  likp.abssc AS payment_guarantee_procedure_abssc,
  likp.kouhr AS picking_time_kouhr,
  likp.tduhr AS transportation_planning_time_tduhr,
  likp.lduhr AS loading_time_lduhr,
  likp.wauhr AS goods_issue_time_wauhr,
  likp.lgtor AS warehouse_door_number_lgtor,
  likp.lgbzo AS warehouse_staging_area_lgbzo,
  likp.akwae AS foreign_trade_currency_key_akwae,
  likp.akkur AS foreign_trade_exchange_rate_akkur,
  likp.akprz AS depreciation_percentage_akprz,
  likp.proli AS dangerous_goods_management_profile_proli,
  likp.xblnr AS reference_document_number_xblnr,
  likp.handle AS worldwide_unique_key_handle,
  likp.tsegfl AS time_segment_exists_indicator_tsegfl,
  likp.tsegtp AS event_group_time_segment_delivery_header_tsegtp,
  likp.tzonis AS delivery_location_timezone_tzonis,
  likp.tzonrc AS recipient_location_timezone_tzonrc,
  likp.cont_dg AS dangerous_goods_indicator_cont_dg,
  likp.verursys AS distribution_delivery_original_system_verursys,
  likp.kzwab AS goods_movement_control_indicator_kzwab,
  likp.vlstk AS distribution_status_vlstk,
  likp.tcode AS transaction_code_tcode,
  likp.vsart AS shipping_type_vsart,
  likp.trmtyp AS means_of_transport_trmtyp,
  likp.sdabw AS special_processing_indicator_sdabw,
  likp.vbund AS company_id_vbund,
  likp.xwoff AS calculation_of_value_open_indicator_xwoff,
  likp.dirta AS automatic_transportation_order_creation_indicator_dirta,
  likp.prvbe AS production_supply_area_prvbe,
  likp.folar AS delivery_type_folar,
  likp.podat AS proof_of_delivery_date_podat,
  likp.potim AS proof_of_delivery_confirmation_time_potim,
  likp.vganz AS shipment_document_total_count_vganz,
  likp.imwrk AS goods_movement_within_company_code_indicator_imwrk,
  likp.spe_loekz AS document_deletion_indicator_spe_loekz,
  likp.spe_loc_seq AS locations_sequenece_number_spe_loc_seq,
  likp.spe_acc_app_sts AS delivery_confirmation_status_spe_acc_app_sts,
  likp.spe_shp_inf_sts AS shipment_information_status_spe_shp_inf_sts,
  likp.spe_ret_canc AS return_document_cancellation_indicator_spe_ret_canc,
  likp.spe_wauhr_ist AS goods_issue_time_spe_wauhr_ist,
  likp.spe_wazone_ist AS goods_issue_time_zone_spe_wazone_ist,
  likp.spe_rev_vlstk AS revenue_recognition_status_spe_rev_vlstk,
  likp.spe_le_scenario AS logistics_execution_scenario_spe_le_scenario,
  likp.spe_orig_sys AS original_system_type_spe_orig_sys,
  likp.spe_chng_sys AS last_changer_system_type_spe_chng_sys,
  likp.spe_georoute AS geographical_route_description_spe_georoute,
  likp.spe_georouteind AS route_change_indicator_spe_georouteind,
  likp.spe_carrier_ind AS carrier_change_indicator_spe_carrier_ind,
  likp.spe_gts_rel AS goods_traffic_type_spe_gts_rel,
  likp.spe_gts_rt_cde AS sap_global_trade_services_route_code_spe_gts_rt_cde,
  likp.spe_rel_tmstmp AS release_time_stamp_spe_rel_tmstmp,
  likp.spe_unit_system AS measurement_unit_system_spe_unit_system,
  likp.spe_inv_bfr_gi AS invoice_creation_before_goods_issue_spe_inv_bfr_gi,
  likp.spe_qi_status AS return_delivery_quality_inspection_status_spe_qi_status,
  likp.spe_red_ind AS redirection_indicator_spe_red_ind,
  likp.sakes AS sap_global_trade_services_delivery_storage_status_sakes,
  likp.spe_lifex_type AS external_identification_type_spe_lifex_type,
  likp.spe_ttype AS means_of_transport_spe_ttype,
  likp.spe_pro_number AS progressive_identification_number_spe_pro_number,
  likp.loc_guid AS location_guid_loc_guid,
  likp.spe_billing_ind AS ewm_billing_indicator_spe_billing_ind,
  likp.printer_profile AS print_profile_description_printer_profile,
  likp.msr_active AS advanced_returns_management_active_msr_active,
  likp.prtnr AS confirmation_number_prtnr,
  likp.stge_loc_change AS storage_location_change_stge_loc_change,
  likp.tm_ctrl_key AS document_transfer_control_key_tm_ctrl_key,
  likp.dlv_split_initia AS delivery_split_initiator_dlv_split_initia,
  likp.dlv_version AS delivery_version_dlv_version,
  likp.gts_vorpa AS previous_document_type_gts_vorpa,
  likp.gts_vornu AS previous_document_number_gts_vornu,
  likp.gts_expvz AS intrastat_border_mode_of_transport_gts_expvz,
  likp.gts_porti AS port_airport_gts_porti,
  likp.itm_expvz AS border_means_of_transport_itm_expvz,
  likp.itm_stgbe AS origin_border_means_of_transport_itm_stgbe,
  likp.itm_kzgbe AS border_cross_means_of_transport_id_itm_kzgbe,
  likp.itm_vygid AS cross_border_conveyance_reference_id_itm_vygid,
  likp.itm_iever AS inland_means_of_transport_itm_iever,
  likp.itm_stabe AS country_of_origin_means_of_transport_itm_stabe,
  likp.itm_kzabe AS inland_means_of_transport_id_itm_kzabe,
  likp.handoverloc AS handover_location_handoverloc,
  likp.handoverdate AS handover_date_handoverdate,
  likp.handovertime AS handover_time_handovertime,
  likp.handovertzone AS handover_time_zone_handovertzone,
  likp.bestk AS delivery_confirmation_status_bestk,
  likp.cmpsc AS maximum_document_value_credit_check_status_cmpsc,
  likp.cmpsd AS terms_of_payment_credit_check_status_cmpsd,
  likp.cmpsi AS financial_document_credit_check_status_cmpsi,
  likp.cmpsj AS export_credit_insurance_credit_check_status_cmpsj,
  likp.cmpsk AS payment_card_authorization_credit_check_status_cmpsk,
  likp.cmps_cm AS sap_credit_management_credit_check_status_cmps_cm,
  likp.cmps_te AS sap_credit_management_technical_error_status_cmps_te,
  likp.cmgst AS credit_checks_overall_status_cmgst,
  likp.fkivk AS intercompany_billing_status_fkivk,
  likp.fkstk AS delivery_related_billing_status_fkstk,
  likp.gbstk AS overall_processing_status_gbstk,
  likp.hdall AS incomplete_inbound_delivery_header_indicator_hdall,
  likp.hdals AS incomplete_inbound_delivery_item_indicator_hdals,
  likp.koquk AS pick_confirmation_status_koquk,
  likp.kostk AS picking_status_kostk,
  likp.lvstk AS warehouse_management_status_lvstk,
  likp.pdstk AS pod_header_status_pdstk,
  likp.pkstk AS packing_status_pkstk,
  likp.spe_tmpid AS temporary_inbound_delivery_indicator_spe_tmpid,
  likp.spstg AS overall_header_block_status_spstg,
  likp.trsta AS transportation_planning_status_trsta,
  likp.uvall AS header_incompletion_status_uvall,
  likp.uvals AS items_incompletion_status_uvals,
  likp.uvfak AS header_billing_incompletion_status_uvfak,
  likp.uvfas AS items_billing_incompletion_status_uvfas,
  likp.uvpak AS header_packing_incompletion_status_uvpak,
  likp.uvpas AS items_packing_incompletion_status_uvpas,
  likp.uvpik AS header_picking_incompletion_status_uvpik,
  likp.uvpis AS items_picking_incompletion_status_uvpis,
  likp.uvvlk AS header_delivery_incompletion_status_uvvlk,
  likp.uvvls AS items_delivery_incompletion_status_uvvls,
  likp.uvwak AS header_goods_movement_incompletion_status_uvwak,
  likp.uvwas AS items_goods_movement_incompletion_status_uvwas,
  likp.vestk AS handling_unit_in_stock_indicator_vestk,
  likp.wbstk AS goods_movement_status_wbstk,
  likp.uvk01 AS header_customer_reserve_status1_suvk01,
  likp.uvk02 AS header_customer_reserve_status2_suvk02,
  likp.uvk03 AS header_customer_reserve_status3_suvk03,
  likp.uvk04 AS header_customer_reserve_status4_suvk04,
  likp.uvk05 AS header_customer_reserve_status5_suvk05,
  likp.uvs01 AS item_customer_reserve_status1_suvs01,
  likp.uvs02 AS item_customer_reserve_status2_suvs02,
  likp.uvs03 AS item_customer_reserve_status3_suvs03,
  likp.uvs04 AS item_customer_reserve_status4_suvs04,
  likp.uvs05 AS item_customer_reserve_status5_suvs05,
  likp.total_pcsta AS total_product_marketability_check_status_total_pcsta,
  likp.total_dgsta AS total_dangerous_goods_check_status_total_dgsta,
  likp.total_sdssta AS total_safety_data_sheet_check_status_total_sdssta,
  likp.total_arc_status AS excise_tax_total_header_status_total_arc_status,
  likp.sapmp_lbask AS dtuc_status_sapmp_lbask,
  likp.incov AS incoterms_version_incov,
  likp.inco2_l AS incoterms_location_1_inco2_l,
  likp.inco3_l AS incoterms_location_2_inco3_l,
  likp.oid_extbol AS external_billing_of_lading_oid_extbol,
  likp.oid_miscdl AS miscellaneous_delivery_number_oid_miscdl,
  likp.ext_bus_syst_id AS external_business_system_id_ext_bus_syst_id,
  likp.sitkz_db AS valuated_stock_in_transit_issue_specification_sitkz_db,
  likp.tm_adv_ship_recv AS advanced_shipping_receipt_relevance_indicator_tm_adv_ship_recv,
  likp.tm_whse_exec AS warehouse_execution_status_tm_whse_exec,
  likp.bev1_luleinh AS loading_units_bev1_luleinh,
  likp.bev1_rpfaess AS number_category_1_bev1_rpfaess,
  likp.bev1_rpkist AS number_category_2_bev1_rpkist,
  likp.bev1_rpcont AS number_category_3_bev1_rpcont,
  likp.bev1_rpsonst AS number_category_4_bev1_rpsonst,
  likp.bev1_rpflgnr AS tour_loading_sequqnce_number_bev1_rpflgnr,
  likp.idt_cur_evtloc AS tracking_last_notified_route_point_idt_cur_evtloc,
  likp.idt_cur_evtqua AS tracking_arrival_departure_indicator_idt_cur_evtqua,
  likp.idt_cur_evttst AS tracking_current_point_event_timestamp_idt_cur_evttst,
  likp.idt_cur_estloc AS tracking_current_point_time_estimation_base_point_idt_cur_estloc,
  likp.idt_cur_estqua AS tracking_current_point_arrival_departure_time_estimation_idt_cur_estqua,
  likp.idt_cur_esttst AS tracking_current_point_delivery_date_estimation_base_date_idt_cur_esttst,
  likp.idt_cur_wrkqua AS tracking_current_point_entry_qualifiers_idt_cur_wrkqua,
  likp.idt_pre_evtloc AS tracking_prior_point_idt_pre_evtloc,
  likp.idt_pre_evtqua AS tracking_prior_point_arrival_departure_indicator_idt_pre_evtqua,
  likp.idt_pre_evttst AS tracking_prior_point_event_timestamp_idt_pre_evttst,
  likp.idt_pre_estloc AS tracking_prior_point_time_estimation_base_point_idt_pre_estloc,
  likp.idt_pre_estqua AS tracking_prior_point_arrival_departure_time_estimation_idt_pre_estqua,
  likp.idt_pre_esttst AS tracking_prior_point_delivery_date_estimation_base_date_idt_pre_esttst,
  likp.idt_pre_wrkqua AS tracking_prior_point_entry_qualifiers_idt_pre_wrkqua,
  likp.idt_ref_estloc AS tracking_reference_point_time_estimation_base_point_idt_ref_estloc,
  likp.idt_ref_estqua AS tracking_reference_point_arrival_departure_time_estimation_idt_ref_estqua,
  likp.idt_ref_esttst AS tracking_reference_point_delivery_date_estimation_base_date_idt_ref_esttst,
  likp.idt_firm_lfdat AS delivery_date_time_commitment_level_idt_firm_lfdat,
  likp.idt_docnum AS document_number_idt_docnum,
  likp.borgr_grp AS multi_level_goods_receipt_automotive_borgr_grp,
  likp.kbnkz AS kanban_indicator_kbnkz,
  likp.rfm_psst_group AS psst_group_rfm_psst_group,
  likp.jit_rlvnt AS jit_relevant_indicator_jit_rlvnt,
  dimensional_date_lfdat.cal_year AS year_of_delivery_date_lfdat,
  dimensional_date_lfdat.cal_month AS month_of_delivery_date_lfdat,
  dimensional_date_lfdat.cal_quarter AS quarter_of_delivery_date_lfdat,
  dimensional_date_lfdat.cal_week AS week_of_delivery_date_lfdat,
  dimensional_date_podat.cal_year AS year_of_proof_of_delivery_date_podat,
  dimensional_date_podat.cal_month AS month_of_proof_of_delivery_date_podat,
  dimensional_date_podat.cal_quarter AS quarter_of_proof_of_delivery_date_podat,
  dimensional_date_podat.cal_week AS week_of_proof_of_delivery_date_podat,
  dimensional_date_bldat.cal_year AS year_of_document_date_bldat,
  dimensional_date_bldat.cal_month AS month_of_document_date_bldat,
  dimensional_date_bldat.cal_quarter AS quarter_of_document_date_bldat,
  dimensional_date_bldat.cal_week AS week_of_document_date_bldat,
  IFNULL(
    likp.recordstamp,
    TIMESTAMP('1900-01-01 00:00:00+00')
  ) AS source_last_updated_at,
  CURRENT_TIMESTAMP() AS bq_loaded_at   
  FROM
  ${ctx.ref(moduleConfig.sources.sapModule.datasetId, "likp")} AS likp
LEFT JOIN currency_decimal
  ON likp.waerk = currency_decimal.currkey
LEFT JOIN date_dimension AS dimensional_date_lfdat
  ON likp.lfdat = dimensional_date_lfdat.date
LEFT JOIN date_dimension AS dimensional_date_podat
  ON likp.podat = dimensional_date_podat.date
LEFT JOIN date_dimension AS dimensional_date_bldat
  ON likp.bldat = dimensional_date_bldat.date
${incremental.getWhere(ctx, "likp.recordstamp")}
`,
);