/**
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

const moduleContext = {
  "moduleId": "sap_customers"
};
const tableConfig = {
  "tags": [
    "sap",
    "dataproduct",
    "masterdata"
  ],
  "materializationType": "incremental",
  "description": "Information about the customer master data, customer number, name of customer, location, address, etc. at the granularity of Client(System) and Customer number, Version ID for International Addresses and Valid from date.",
  "columns": {
    "client_mandt": "Client (Mandant), PK",
    "customer_number_kunnr": "Customer Number, PK",
    "valid_from_date_date_from": "Valid-from date, PK",
    "version_id_for_international_addresses_nation": "Version ID for International Addresses, PK",
    "country_key_land1": "Country Key",
    "name1_name1": "Name 1",
    "name2_name2": "Name 2",
    "city_ort01": "City",
    "postal_code_pstlz": "Postal Code",
    "customer_region_regio": "Region (State, Province, Country)",
    "sort_field_sortl": "Sort Field",
    "street_and_number_stras": "Street and House Number",
    "first_telephone_number_telf1": "First Telephone Number",
    "fax_number_telfx": "Fax Number",
    "one_time_account_xcpdk": "Indicator: Is the Account a One-Time Account?",
    "address_adrnr": "Address",
    "matchcode_search_mcod1": "Search Term for Matchcode Search",
    "matchcode_search_mcod2": "Search Term 2 for Matchcode Search",
    "matchcode_search_mcod3": "Search Term 3 for Matchcode Search",
    "title_anred": "Title",
    "central_order_block_for_customer_aufsd": "Central Order Block for Customer",
    "express_train_station_bahne": "Express Train Station",
    "train_station_bahns": "Train Station",
    "international_location_number_bbbnr": "International Location Number (Part 1)",
    "international_location_number_bbsnr": "International Location Number (Part 2)",
    "authorization_group_begru": "Authorization Group",
    "industry_key_brsch": "Industry Key",
    "check_digit_for_the_international_location_number_bubkz": "Check Digit for the International Location Number",
    "data_communication_line_no_datlt": "Data Communication Line Number",
    "date_created_erdat": "Date on which the Record Was Created",
    "created_by_ernam": "Name of Person who Created the Object",
    "unloading_points_exist_exabl": "Indicator: Unloading points exist",
    "central_billing_block_faksd": "Central billing block for Customer",
    "account_number_fiscal_address_fiskn": "Account Number of the Master Record with the Fiscal Address",
    "working_time_calendar_knazk": "Working Time Calendar",
    "alternative_payer_knrza": "Account Number of an Alternative Payer",
    "group_key_konzs": "Group Key",
    "customer_account_group_ktokd": "Customer Account Group",
    "customer_classification_kukla": "Customer Classification",
    "account_number_of_vendor_or_creditor_lifnr": "Account Number of Vendor or Creditor",
    "central_delivery_block_for_the_customer_lifsd": "Central Delivery Block for the Customer",
    "city_coordinates_locco": "City Coordinates",
    "central_deletion_flag_for_master_record_loevm": "Central Deletion Flag for Master Record",
    "name3_name3": "Name 3",
    "name4_name4": "Name 4",
    "nielsen_id_niels": "Nielsen ID",
    "district_ort02": "District",
    "po_box_pfach": "PO Box",
    "po_box_postal_code_pstl2": "P.O. Box Postal Code",
    "county_code_counc": "County Code",
    "city_code_cityc": "City Code",
    "regional_market_rpmkr": "Regional Market",
    "central_posting_block_sperr": "Central Posting Block",
    "language_key_spras": "Language Key",
    "tax_number1_stcd1": "Tax Number 1",
    "tax_number2_stcd2": "Tax Number 2",
    "subject_to_equalization_tax_stkza": "Indicator: Business Partner Subject to Equalization Tax?",
    "liable_for_vat_stkzu": "Liable for VAT",
    "telebox_number_telbx": "Telebox number",
    "second_telephone_number_telf2": "Second Telephone Number",
    "teletex_number_teltx": "Teletex number",
    "telex_number_telx1": "Telex number",
    "transportation_zone_lzone": "Transportation Zone to or from which the goods are delivered",
    "alternative_payer_allowed_xzemp": "Indicator: Is an alternative payer allowed in document?",
    "company_id_of_trading_partner_vbund": "Company ID of Trading Partner",
    "vat_registration_number_stceg": "VAT Registration Number",
    "competitor_dear1": "Indicator: Competitor",
    "sales_partner_dear2": "Indicator: Sales partner",
    "sales_prospect_dear3": "Indicator: Sales Prospect",
    "customer_type4_dear4": "Indicator for Customer type 4",
    "id_for_default_sold_to_party_dear5": "ID for Default Sold-to Party",
    "legal_status_gform": "Legal Status",
    "industry_code1_bran1": "Industry Code 1",
    "industry_code2_bran2": "Industry Code 2",
    "industry_code3_bran3": "Industry Code 3",
    "industry_code4_bran4": "Industry Code 4",
    "industry_code5_bran5": "Industry Code 5",
    "initial_contact_ekont": "Initial Contact",
    "annual_sales_umsat": "Annual Sales",
    "year_for_which_sales_are_given_umjah": "Year For Which Sales are Given",
    "currency_of_sales_figure_uwaer": "Currency of Sales figures",
    "yearly_number_of_employees_jmzah": "Yearly number of Employees",
    "year_for_which_the_number_of_employees_is_given_jmjah": "Year for which the Number of Employees is Given",
    "attribute1_katr1": "Attribute 1",
    "attribute2_katr2": "Attribute 2",
    "attribute3_katr3": "Attribute 3",
    "attribute4_katr4": "Attribute 4",
    "attribute5_katr5": "Attribute 5",
    "attribute6_katr6": "Attribute 6",
    "attribute7_katr7": "Attribute 7",
    "attribute8_katr8": "Attribute 8",
    "attribute9_katr9": "Attribute 9",
    "attribute10_katr10": "Attribute 10",
    "natural_person_stkzn": "Natural Person",
    "annual_sales_umsa1": "Annual Sales",
    "tax_jurisdiction_txjcd": "Tax Jurisdiction",
    "fiscal_year_variant_periv": "Fiscal Year Variant",
    "usage_indicator_abrvw": "Usage Indicator",
    "inspection_carried_out_by_customer_inspbydebi": "Inspection Carried Out By Customer (No Inspection Lot)",
    "inspection_for_a_delivery_note_inspatdebi": "Inspection for a Delivery Note After Outbound Delivery",
    "reference_account_group_ktocd": "Reference Account Group for One-Time Account (Customer)",
    "po_box_city_pfort": "PO Box city",
    "plant_werks": "Plant",
    "report_key_for_data_medium_exchange_dtams": "Report key for Data Medium Exchange ",
    "instruction_key_for_data_medium_exchange_dtaws": "Instruction key for Data Medium Exchange",
    "status_of_data_transfer_into_subsequent_release_duefl": "Status of Data Transfer to Next Release",
    "assignment_to_hierarchy_hzuor": "Assignment to Hierarchy",
    "payment_block_sperz": "Payment Block",
    "r_labeling_customerplant_group_etikg": "IS-R Labeling: Customer/Plant Group",
    "id_non_military_use_civve": "ID for mainly Non-Military Use",
    "id_for_military_use_milve": "ID for mainly Military Use",
    "condition_group1_kdkg1": "Customer Condition group 1",
    "condition_group2_kdkg2": "Customer Condition group 2",
    "condition_group3_kdkg3": "Customer Condition group 3",
    "condition_group4_kdkg4": "Customer Condition group 4",
    "condition_group5_kdkg5": "Customer Condition group 5",
    "alternative_payer_using_account_number_xknza": "Indicator: Alternative payer using Account Number",
    "tax_type_fityp": "Tax Type",
    "tax_number_type_stcdt": "Tax Number Type",
    "tax_number3_stcd3": "Tax Number 3",
    "tax_number4_stcd4": "Tax Number 4",
    "tax_number5_stcd5": "Tax Number 5",
    "customer_is_icms_exempt_xicms": "Customer is ICMS-exempt",
    "customer_is_ipi_exempt_xxipi": "Customer is IPI-exempt",
    "customer_group_for_substituicao_tributaria_calculation_xsubt": "Customer Group for Substituicao Tributaria group",
    "customer_cfop_category_cfopc": "Customer's CFOP Category",
    "tax_law_icms_txlw1": "Tax law: ICMS",
    "tax_law_ipi_txlw2": "Tax law: IPI",
    "indicator_for_biochemical_warfare_ccc01": "Indicator for Biochemical Warfare for Legal Control",
    "indicator_for_nuclear_nonproliferation_ccc02": "Indicator for Nuclear Nonproliferation for Legal Control",
    "indicator_for_national_security_ccc03": "Indicator for National Security for Legal Control",
    "indicator_for_missile_technology_ccc04": "Indicator for Missile Technology for Legal Control",
    "central_sales_block_cassd": "Central Sales Block for Customer",
    "uniform_resource_locator_knurl": "Uniform Resource Locator",
    "name_of_representative_j_1_kfrepre": "Name of Representative",
    "type_of_business_j_1_kftbus": "Type of Business",
    "type_of_industry_j_1_kftind": "Type of Industry",
    "status_of_change_authorization_confs": "Status of Change Authorization (Central)",
    "date_on_which_the_changes_were_confirmed_updat": "Date on Which the Changes Were Confirmed",
    "time_of_last_change_confirmation_uptim": "Time of Last Change Confirmation",
    "central_deletion_block_for_master_record_nodel": "Central Deletion Block for Master Record",
    "indicator_consumer_dear6": "Indicator: Consumer",
    "business_purpose_completed_flag_cvp_xblck": "Business Purpose Completed Flag",
    "suframa_code_suframa": "Suframa Code",
    "rg_number_rg": "RG Number",
    "issued_by_exp": "Issued By",
    "state_uf": "State",
    "rg_issuing_date_rgdate": "RG Issuing Date",
    "ric_number_ric": "RIC Number",
    "foreign_national_registration_rne": "Foreign National Registration",
    "rne_issuing_date_rnedate": "RNE Issuing Date",
    "cnae_cnae": "CNAE",
    "legal_nature_legalnat": "Legal Nature",
    "crt_number_crtn": "CRT Number",
    "icms_taxpayer_icmstaxpay": "ICMS Taxpayer",
    "industry_main_type_indtyp": "Industry Main Type",
    "tax_declaration_type_tdt": "Tax Declaration Type",
    "company_size_comsize": "Company Size",
    "declaration_regimen_for_piscofins_decregpc": "Declaration Regimen for PIS/COFINS",
    "agency_location_code_alc": "Agency Location Code",
    "payment_office_pmt_office": "Payment Office",
    "fee_schedule_fee_schedule": "Fee Schedule",
    "duns_number_duns": "DUNS Number",
    "duns4_duns4": "DUNS+4",
    "processor_group_psofg": "Processor group",
    "subledger_acct_preprocessing_procedure_psois": "Subledger acct Preprocessing Procedure",
    "name1_pson1": "Name 1",
    "name2_pson2": "Name 2",
    "name3_pson3": "Name 3",
    "first_name_psovn": "First Name",
    "title_psotl": "Title",
    "description_psoo1": "Description",
    "description_psoo2": "Description",
    "description_psoo3": "Description",
    "description_psoo4": "Description",
    "description_psoo5": "Description",
    "address_number_addrnumber": "Address Number",
    "valid_to_date_date_to": "Valid-to date",
    "form_of_address_key_title": "Form-of-Address Key",
    "addr_name1": "Name 1",
    "addr_name2": "Name 2",
    "addr_name3": "Name 3",
    "addr_name4": "Name 4",
    "city_city1": "City",
    "district_city2": "District",
    "city_code_for_citystreet_file_city_code": "City Code for City/Street file",
    "district_code_for_city_and_street_file_cityp_code": "District Code for City/Street file",
    "city_home_city": "City (Different from Postal City)",
    "different_city_for_citystreet_file_cityh_code": "Different City for City/Street file",
    "regional_structure_grouping_regiogroup": "Regional Structure Grouping",
    "city_postal_code_post_code1": "City Postal Code",
    "po_box_postal_code_post_code2": "PO Box Postal Code",
    "company_postal_code_post_code3": "Company Postal Code (for Large Customers)",
    "po_box_po_box": "PO Box",
    "po_box_address_undeliverable_flag_dont_use_p": "PO Box Address Undeliverable Flag",
    "flag_po_box_without_number_po_box_num": "Flag: PO Box Without Number",
    "po_box_city_po_box_loc": "PO Box City",
    "city_po_box_code_city_file_city_code2": "City PO Box Code (City file)",
    "region_for_po_box_po_box_reg": "Region for PO Box (Country, State, Province, ...)",
    "po_box_country_po_box_cty": "PO Box Country",
    "transportation_zone_to_or_from_which_the_goods_are_delivered_transpzone": "Transportation Zone to or from which the Goods are Delivered",
    "street_street": "Street",
    "street_address_undeliverable_flag_dont_use_s": "Street Address Undeliverable Flag",
    "street_number_for_citystreet_file_streetcode": "Street Number for City/Street File",
    "house_number_house_num1": "House Number",
    "house_number_supplement_house_num2": "House Number Supplement",
    "street2_str_suppl1": "Street 2",
    "street3_str_suppl2": "Street 3",
    "street4_str_suppl3": "Street 4",
    "street5_location": "Street 5",
    "building_number_or_code_building": "Building (Number or Code)",
    "floor_in_building_floor": "Floor in Building",
    "room_or_appartment_number_roomnumber": "Room or Apartment Number",
    "country_key_country": "Country Key",
    "language_langu": "Language Key",
    "region_region": "Region (State, Province, County)",
    "address_group_key_business_address_services_addr_group": "Address Group (Key) (Business Address Services)",
    "flag_there_are_more_address_group_assignments_flaggroups": "Flag: There are more address group assignments",
    "flag_this_is_a_personal_address_pers_addr": "Flag: This is a personal address",
    "search_term1_sort1": "Search Term 1",
    "search_term2_sort2": "Search Term 2",
    "first_telephone_no_dialling_codenumber_tel_number": "First Telephone Number: Dialling Code + Number",
    "first_telephone_no_extension_tel_extens": "First Telephone Number: Extension",
    "county_code_for_county_county_code": "County Code for County",
    "county_county": "County",
    "township_code_for_township_township_code": "Township Code for Township",
    "township_township": "Township",
    "county_name_in_upper_case_for_search_help_mc_county": "County Name is Upper Case for Search Help",
    "township_name_in_upper_case_for_search_help_mc_township": "Township Name is Upper Case for Search Help",
    "business_purpose_completed_flag_xpcpt": "Business Purpose Completed Flag",
    "source_last_updated_at": "Timestamp when the source record was last updated",
    "bq_loaded_at": "Timestamp when the record was loaded into BigQuery"
  }
};
const moduleConfig = config.product[moduleContext.moduleId];

const materializationType = tableConfig.materializationType || "incremental";

const incremental = require("includes/cortex/incremental.js");
const publish_config = require("includes/cortex/publish_config.js");

const publishConfig = publish_config.getPublishConfig(
  materializationType,
  tableConfig,
  moduleConfig,
  [
    "client_mandt",
    "customer_number_kunnr",
    "address_adrnr",
    "valid_from_date_date_from",
    "version_id_for_international_addresses_nation",
  ]
);

publish("customers_md", publishConfig).query(
  (ctx) => `
    SELECT
      kna1.mandt AS client_mandt,
      kna1.kunnr AS customer_number_kunnr,
      kna1.land1 AS country_key_land1,
      kna1.name1 AS name1_name1,
      kna1.name2 AS name2_name2,
      kna1.ort01 AS city_ort01,
      COALESCE(kna1.pstlz, adrc.post_code1) AS postal_code_pstlz,
      COALESCE(kna1.regio, adrc.region) AS customer_region_regio,
      kna1.sortl AS sort_field_sortl,
      kna1.stras AS street_and_number_stras,
      kna1.telf1 AS first_telephone_number_telf1,
      kna1.telfx AS fax_number_telfx,
      kna1.xcpdk AS one_time_account_xcpdk,
      kna1.adrnr AS address_adrnr,
      kna1.mcod1 AS matchcode_search_mcod1,
      kna1.mcod2 AS matchcode_search_mcod2,
      kna1.mcod3 AS matchcode_search_mcod3,
      kna1.anred AS title_anred,
      kna1.aufsd AS central_order_block_for_customer_aufsd,
      kna1.bahne AS express_train_station_bahne,
      kna1.bahns AS train_station_bahns,
      kna1.bbbnr AS international_location_number_bbbnr,
      kna1.bbsnr AS international_location_number_bbsnr,
      kna1.begru AS authorization_group_begru,
      kna1.brsch AS industry_key_brsch,
      kna1.bubkz AS check_digit_for_the_international_location_number_bubkz,
      kna1.datlt AS data_communication_line_no_datlt,
      kna1.erdat AS date_created_erdat,
      kna1.ernam AS created_by_ernam,
      kna1.exabl AS unloading_points_exist_exabl,
      kna1.faksd AS central_billing_block_faksd,
      kna1.fiskn AS account_number_fiscal_address_fiskn,
      kna1.knazk AS working_time_calendar_knazk,
      kna1.knrza AS alternative_payer_knrza,
      kna1.konzs AS group_key_konzs,
      kna1.ktokd AS customer_account_group_ktokd,
      kna1.kukla AS customer_classification_kukla,
      kna1.lifnr AS account_number_of_vendor_or_creditor_lifnr,
      kna1.lifsd AS central_delivery_block_for_the_customer_lifsd,
      kna1.locco AS city_coordinates_locco,
      kna1.loevm AS central_deletion_flag_for_master_record_loevm,
      kna1.name3 AS name3_name3,
      kna1.name4 AS name4_name4,
      kna1.niels AS nielsen_id_niels,
      kna1.ort02 AS district_ort02,
      kna1.pfach AS po_box_pfach,
      kna1.pstl2 AS po_box_postal_code_pstl2,
      kna1.counc AS county_code_counc,
      kna1.cityc AS city_code_cityc,
      kna1.rpmkr AS regional_market_rpmkr,
      kna1.sperr AS central_posting_block_sperr,
      kna1.spras AS language_key_spras,
      kna1.stcd1 AS tax_number1_stcd1,
      kna1.stcd2 AS tax_number2_stcd2,
      kna1.stkza AS subject_to_equalization_tax_stkza,
      kna1.stkzu AS liable_for_vat_stkzu,
      kna1.telbx AS telebox_number_telbx,
      kna1.telf2 AS second_telephone_number_telf2,
      kna1.teltx AS teletex_number_teltx,
      kna1.telx1 AS telex_number_telx1,
      kna1.lzone AS transportation_zone_lzone,
      kna1.xzemp AS alternative_payer_allowed_xzemp,
      kna1.vbund AS company_id_of_trading_partner_vbund,
      kna1.stceg AS vat_registration_number_stceg,
      kna1.dear1 AS competitor_dear1,
      kna1.dear2 AS sales_partner_dear2,
      kna1.dear3 AS sales_prospect_dear3,
      kna1.dear4 AS customer_type4_dear4,
      kna1.dear5 AS id_for_default_sold_to_party_dear5,
      kna1.gform AS legal_status_gform,
      kna1.bran1 AS industry_code1_bran1,
      kna1.bran2 AS industry_code2_bran2,
      kna1.bran3 AS industry_code3_bran3,
      kna1.bran4 AS industry_code4_bran4,
      kna1.bran5 AS industry_code5_bran5,
      kna1.ekont AS initial_contact_ekont,
      kna1.umsat AS annual_sales_umsat,
      kna1.umjah AS year_for_which_sales_are_given_umjah,
      kna1.uwaer AS currency_of_sales_figure_uwaer,
      kna1.jmzah AS yearly_number_of_employees_jmzah,
      kna1.jmjah AS year_for_which_the_number_of_employees_is_given_jmjah,
      kna1.katr1 AS attribute1_katr1,
      kna1.katr2 AS attribute2_katr2,
      kna1.katr3 AS attribute3_katr3,
      kna1.katr4 AS attribute4_katr4,
      kna1.katr5 AS attribute5_katr5,
      kna1.katr6 AS attribute6_katr6,
      kna1.katr7 AS attribute7_katr7,
      kna1.katr8 AS attribute8_katr8,
      kna1.katr9 AS attribute9_katr9,
      kna1.katr10 AS attribute10_katr10,
      kna1.stkzn AS natural_person_stkzn,
      kna1.umsa1 AS annual_sales_umsa1,
      kna1.txjcd AS tax_jurisdiction_txjcd,
      kna1.periv AS fiscal_year_variant_periv,
      kna1.abrvw AS usage_indicator_abrvw,
      kna1.inspbydebi AS inspection_carried_out_by_customer_inspbydebi,
      kna1.inspatdebi AS inspection_for_a_delivery_note_inspatdebi,
      kna1.ktocd AS reference_account_group_ktocd,
      kna1.pfort AS po_box_city_pfort,
      kna1.werks AS plant_werks,
      kna1.dtams AS report_key_for_data_medium_exchange_dtams,
      kna1.dtaws AS instruction_key_for_data_medium_exchange_dtaws,
      kna1.duefl AS status_of_data_transfer_into_subsequent_release_duefl,
      kna1.hzuor AS assignment_to_hierarchy_hzuor,
      kna1.sperz AS payment_block_sperz,
      kna1.etikg AS r_labeling_customerplant_group_etikg,
      kna1.civve AS id_non_military_use_civve,
      kna1.milve AS id_for_military_use_milve,
      kna1.kdkg1 AS condition_group1_kdkg1,
      kna1.kdkg2 AS condition_group2_kdkg2,
      kna1.kdkg3 AS condition_group3_kdkg3,
      kna1.kdkg4 AS condition_group4_kdkg4,
      kna1.kdkg5 AS condition_group5_kdkg5,
      kna1.xknza AS alternative_payer_using_account_number_xknza,
      kna1.fityp AS tax_type_fityp,
      kna1.stcdt AS tax_number_type_stcdt,
      kna1.stcd3 AS tax_number3_stcd3,
      kna1.stcd4 AS tax_number4_stcd4,
      kna1.stcd5 AS tax_number5_stcd5,
      kna1.xicms AS customer_is_icms_exempt_xicms,
      kna1.xxipi AS customer_is_ipi_exempt_xxipi,
      kna1.xsubt AS customer_group_for_substituicao_tributaria_calculation_xsubt,
      kna1.cfopc AS customer_cfop_category_cfopc,
      kna1.txlw1 AS tax_law_icms_txlw1,
      kna1.txlw2 AS tax_law_ipi_txlw2,
      kna1.ccc01 AS indicator_for_biochemical_warfare_ccc01,
      kna1.ccc02 AS indicator_for_nuclear_nonproliferation_ccc02,
      kna1.ccc03 AS indicator_for_national_security_ccc03,
      kna1.ccc04 AS indicator_for_missile_technology_ccc04,
      kna1.cassd AS central_sales_block_cassd,
      kna1.knurl AS uniform_resource_locator_knurl,
      kna1.j_1kfrepre AS name_of_representative_j_1_kfrepre,
      kna1.j_1kftbus AS type_of_business_j_1_kftbus,
      kna1.j_1kftind AS type_of_industry_j_1_kftind,
      kna1.confs AS status_of_change_authorization_confs,
      kna1.updat AS date_on_which_the_changes_were_confirmed_updat,
      kna1.uptim AS time_of_last_change_confirmation_uptim,
      kna1.nodel AS central_deletion_block_for_master_record_nodel,
      kna1.dear6 AS indicator_consumer_dear6,
      kna1.cvp_xblck AS business_purpose_completed_flag_cvp_xblck,
      kna1.suframa AS suframa_code_suframa,
      kna1.rg AS rg_number_rg,
      kna1.exp AS issued_by_exp,
      kna1.uf AS state_uf,
      kna1.rgdate AS rg_issuing_date_rgdate,
      kna1.ric AS ric_number_ric,
      kna1.rne AS foreign_national_registration_rne,
      kna1.rnedate AS rne_issuing_date_rnedate,
      kna1.cnae AS cnae_cnae,
      kna1.legalnat AS legal_nature_legalnat,
      kna1.crtn AS crt_number_crtn,
      kna1.icmstaxpay AS icms_taxpayer_icmstaxpay,
      kna1.indtyp AS industry_main_type_indtyp,
      kna1.tdt AS tax_declaration_type_tdt,
      kna1.comsize AS company_size_comsize,
      kna1.decregpc AS declaration_regimen_for_piscofins_decregpc,
      kna1.alc AS agency_location_code_alc,
      kna1.pmt_office AS payment_office_pmt_office,
      kna1.fee_schedule AS fee_schedule_fee_schedule,
      kna1.duns AS duns_number_duns,
      kna1.duns4 AS duns4_duns4,
      kna1.psofg AS processor_group_psofg,
      kna1.psois AS subledger_acct_preprocessing_procedure_psois,
      kna1.pson1 AS name1_pson1,
      kna1.pson2 AS name2_pson2,
      kna1.pson3 AS name3_pson3,
      kna1.psovn AS first_name_psovn,
      kna1.psotl AS title_psotl,
      kna1.psoo1 AS description_psoo1,
      kna1.psoo2 AS description_psoo2,
      kna1.psoo3 AS description_psoo3,
      kna1.psoo4 AS description_psoo4,
      kna1.psoo5 AS description_psoo5,
      adrc.addrnumber AS address_number_addrnumber,
      adrc.date_from AS valid_from_date_date_from,
      adrc.nation AS version_id_for_international_addresses_nation,
      adrc.date_to AS valid_to_date_date_to,
      adrc.title AS form_of_address_key_title,
      adrc.name1 AS addr_name1,
      adrc.name2 AS addr_name2,
      adrc.name3 AS addr_name3,
      adrc.name4 AS addr_name4,
      adrc.city1 AS city_city1,
      adrc.city2 AS district_city2,
      adrc.city_code AS city_code_for_citystreet_file_city_code,
      adrc.cityp_code AS district_code_for_city_and_street_file_cityp_code,
      adrc.home_city AS city_home_city,
      adrc.cityh_code AS different_city_for_citystreet_file_cityh_code,
      adrc.regiogroup AS regional_structure_grouping_regiogroup,
      adrc.post_code1 AS city_postal_code_post_code1,
      adrc.post_code2 AS po_box_postal_code_post_code2,
      adrc.post_code3 AS company_postal_code_post_code3,
      adrc.po_box AS po_box_po_box,
      adrc.dont_use_p AS po_box_address_undeliverable_flag_dont_use_p,
      adrc.po_box_num AS flag_po_box_without_number_po_box_num,
      adrc.po_box_loc AS po_box_city_po_box_loc,
      adrc.city_code2 AS city_po_box_code_city_file_city_code2,
      adrc.po_box_reg AS region_for_po_box_po_box_reg,
      adrc.po_box_cty AS po_box_country_po_box_cty,
      adrc.transpzone AS transportation_zone_to_or_from_which_the_goods_are_delivered_transpzone,
      adrc.street AS street_street,
      adrc.dont_use_s AS street_address_undeliverable_flag_dont_use_s,
      adrc.streetcode AS street_number_for_citystreet_file_streetcode,
      adrc.house_num1 AS house_number_house_num1,
      adrc.house_num2 AS house_number_supplement_house_num2,
      adrc.str_suppl1 AS street2_str_suppl1,
      adrc.str_suppl2 AS street3_str_suppl2,
      adrc.str_suppl3 AS street4_str_suppl3,
      adrc.location AS street5_location,
      adrc.building AS building_number_or_code_building,
      adrc.floor AS floor_in_building_floor,
      adrc.roomnumber AS room_or_appartment_number_roomnumber,
      adrc.country AS country_key_country,
      adrc.langu AS language_langu,
      adrc.region AS region_region,
      adrc.addr_group AS address_group_key_business_address_services_addr_group,
      adrc.flaggroups AS flag_there_are_more_address_group_assignments_flaggroups,
      adrc.pers_addr AS flag_this_is_a_personal_address_pers_addr,
      adrc.sort1 AS search_term1_sort1,
      adrc.sort2 AS search_term2_sort2,
      adrc.tel_number AS first_telephone_no_dialling_codenumber_tel_number,
      adrc.tel_extens AS first_telephone_no_extension_tel_extens,
      adrc.county_code AS county_code_for_county_county_code,
      adrc.county AS county_county,
      adrc.township_code AS township_code_for_township_township_code,
      adrc.township AS township_township,
      adrc.mc_county AS county_name_in_upper_case_for_search_help_mc_county,
      adrc.mc_township AS township_name_in_upper_case_for_search_help_mc_township,
      adrc.xpcpt AS business_purpose_completed_flag_xpcpt,
      -- SAFE GREATEST: Protects against NULLs if Address is missing
      GREATEST(
        IFNULL(kna1.recordstamp, TIMESTAMP('1900-01-01 00:00:00+00')),
        IFNULL(adrc.recordstamp, TIMESTAMP('1900-01-01 00:00:00+00'))
      ) AS source_last_updated_at,
      CURRENT_TIMESTAMP() AS bq_loaded_at
    FROM 
      ${ctx.ref(moduleConfig.sources.sapModule.datasetId, "kna1")} AS kna1
    LEFT JOIN 
      ${ctx.ref(moduleConfig.sources.sapModule.datasetId, "adrc")} AS adrc
      ON 
        kna1.adrnr = adrc.addrnumber
        AND kna1.mandt = adrc.client
        AND adrc.date_to = CAST('9999-12-31' AS DATE)
    ${incremental.getWhere(ctx, ["kna1.recordstamp", "adrc.recordstamp"])}
      AND COALESCE(adrc.nation, '') = ''
  `,
);
