config {
  type: "operations",
  hasOutput: true,
  database: config.foundation.erp.targetProjectId,
  schema: config.foundation.erp.targetDatasetId,
  name: "t024e",
  tags: ["sap", "common", "configuration", "once"]
}

js {
  const sap_cdc = require("includes/cortex/sap_cdc.js");
}

${sap_cdc.generateIncrementalMergeScript(ctx, {
  keys: [
  "ekorg",
  "mandt"
],
  columns: [
  "mandt",
  "ekorg",
  "ekotx",
  "bukrs",
  "txadr",
  "txkop",
  "txfus",
  "txgru",
  "kalse",
  "mkals",
  "bpeff",
  "bukrs_ntr",
  "configdeprecationcode",
  "operation_flag",
  "is_deleted",
  "recordstamp"
],
  table_description: "Purchasing Organizations",
  column_descriptions: {
  "bpeff": "Effective Price",
  "bukrs": "Company Code",
  "bukrs_ntr": "CoCdSubsStlmt",
  "ekorg": "Purch. Organization",
  "ekotx": "Description",
  "kalse": "PurOrg. Schema Group",
  "mandt": "Client (Mandant)",
  "mkals": "Market Price Schema",
  "txadr": "Text Name: Sender",
  "txfus": "Text Name: Footer",
  "txgru": "Text: Compl. Close",
  "txkop": "Text: Letter Heading"
},
  target_ref: self(),
  source_ref: ref(config.foundation.erp.sourceDatasetId, "t024e")
})}